// This file was auto-generated by Fern from our API Definition.

package api

import (
	json "encoding/json"
	fmt "fmt"
	core "sdk/core"
)

type EndToEndDubbingRequestPayload struct {
	RunID                   *int        `json:"-" url:"run_id,omitempty"`
	ProjectName             *string     `json:"project_name,omitempty" url:"-"`
	ProjectDescription      *string     `json:"project_description,omitempty" url:"-"`
	FolderID                *int        `json:"folder_id,omitempty" url:"-"`
	VideoURL                string      `json:"video_url" url:"-"`
	SourceLanguage          Languages   `json:"source_language" url:"-"`
	TargetLanguage          *Languages  `json:"target_language,omitempty" url:"-"`
	TargetLanguages         []Languages `json:"target_languages,omitempty" url:"-"`
	SelectedAudioTracks     []int       `json:"selected_audio_tracks,omitempty" url:"-"`
	AddOutputAsAnAudioTrack *bool       `json:"add_output_as_an_audio_track,omitempty" url:"-"`
	ChosenDictionaries      []int       `json:"chosen_dictionaries,omitempty" url:"-"`
	AiOptimization          *bool       `json:"ai_optimization,omitempty" url:"-"`
}

type DubbedOutputInAltFormatRequestPayload struct {
	OutputFormat *DubbedOutputInAltFormatRequestPayloadOutputFormat `json:"output_format,omitempty" url:"-"`
}

type GetDubbedOutputInAltFormatStatusDubAltFormatTaskIDGetRequest struct {
	RunID *int `json:"-" url:"run_id,omitempty"`
}

type GetDubbedRunInfoDubResultRunIDGetRequest struct {
}

type GetDubbedRunTranscriptTranscriptRunIDLanguageGetRequest struct {
	// Format to use for the transcription. Either `srt`, `vtt` or `txt`. Defaults to `txt`.
	FormatType *TranscriptFileFormat `json:"-" url:"format_type,omitempty"`
	// Data type for the transcription being returned. Returns the raw data of the transcription or a presigned url for the file that holds the transcription data.
	DataType *TranscriptDataType `json:"-" url:"data_type,omitempty"`
}

type GetDubbingRunsResultsDubbingResultsPostRequest struct {
	Traceparent *string               `json:"-" url:"-"`
	RunID       *int                  `json:"-" url:"run_id,omitempty"`
	Body        *RunIDsRequestPayload `json:"-" url:"-"`
}

func (g *GetDubbingRunsResultsDubbingResultsPostRequest) UnmarshalJSON(data []byte) error {
	body := new(RunIDsRequestPayload)
	if err := json.Unmarshal(data, &body); err != nil {
		return err
	}
	g.Body = body
	return nil
}

func (g *GetDubbingRunsResultsDubbingResultsPostRequest) MarshalJSON() ([]byte, error) {
	return json.Marshal(g.Body)
}

type GetEndToEndDubbingStatusDubTaskIDGetRequest struct {
	RunID *int `json:"-" url:"run_id,omitempty"`
}

type PollDiscordDubTaskDiscordDubTaskIDGetRequest struct {
	RunID *int `json:"-" url:"run_id,omitempty"`
}

type PollTwitterDubTaskTwitterDubTaskIDGetRequest struct {
	RunID *int `json:"-" url:"run_id,omitempty"`
}

type AudioOutputType string

const (
	AudioOutputTypeFlac AudioOutputType = "flac"
	AudioOutputTypeWav  AudioOutputType = "wav"
	AudioOutputTypeMp3  AudioOutputType = "mp3"
	AudioOutputTypeAac  AudioOutputType = "aac"
	AudioOutputTypeM4A  AudioOutputType = "m4a"
)

func NewAudioOutputTypeFromString(s string) (AudioOutputType, error) {
	switch s {
	case "flac":
		return AudioOutputTypeFlac, nil
	case "wav":
		return AudioOutputTypeWav, nil
	case "mp3":
		return AudioOutputTypeMp3, nil
	case "aac":
		return AudioOutputTypeAac, nil
	case "m4a":
		return AudioOutputTypeM4A, nil
	}
	var t AudioOutputType
	return "", fmt.Errorf("%s is not a valid %T", s, t)
}

func (a AudioOutputType) Ptr() *AudioOutputType {
	return &a
}

type DubbingResult struct {
	AudioURL   string        `json:"audio_url" url:"audio_url"`
	Transcript []*Transcript `json:"transcript,omitempty" url:"transcript,omitempty"`
	VideoURL   *string       `json:"video_url,omitempty" url:"video_url,omitempty"`

	extraProperties map[string]interface{}
	_rawJSON        json.RawMessage
}

func (d *DubbingResult) GetAudioURL() string {
	if d == nil {
		return ""
	}
	return d.AudioURL
}

func (d *DubbingResult) GetTranscript() []*Transcript {
	if d == nil {
		return nil
	}
	return d.Transcript
}

func (d *DubbingResult) GetVideoURL() *string {
	if d == nil {
		return nil
	}
	return d.VideoURL
}

func (d *DubbingResult) GetExtraProperties() map[string]interface{} {
	return d.extraProperties
}

func (d *DubbingResult) UnmarshalJSON(data []byte) error {
	type unmarshaler DubbingResult
	var value unmarshaler
	if err := json.Unmarshal(data, &value); err != nil {
		return err
	}
	*d = DubbingResult(value)

	extraProperties, err := core.ExtractExtraProperties(data, *d)
	if err != nil {
		return err
	}
	d.extraProperties = extraProperties

	d._rawJSON = json.RawMessage(data)
	return nil
}

func (d *DubbingResult) String() string {
	if len(d._rawJSON) > 0 {
		if value, err := core.StringifyJSON(d._rawJSON); err == nil {
			return value
		}
	}
	if value, err := core.StringifyJSON(d); err == nil {
		return value
	}
	return fmt.Sprintf("%#v", d)
}

type TranscriptDataType string

const (
	TranscriptDataTypeRawData TranscriptDataType = "raw_data"
	TranscriptDataTypeFile    TranscriptDataType = "file"
)

func NewTranscriptDataTypeFromString(s string) (TranscriptDataType, error) {
	switch s {
	case "raw_data":
		return TranscriptDataTypeRawData, nil
	case "file":
		return TranscriptDataTypeFile, nil
	}
	var t TranscriptDataType
	return "", fmt.Errorf("%s is not a valid %T", s, t)
}

func (t TranscriptDataType) Ptr() *TranscriptDataType {
	return &t
}

type TranscriptFileFormat string

const (
	TranscriptFileFormatSrt TranscriptFileFormat = "srt"
	TranscriptFileFormatVtt TranscriptFileFormat = "vtt"
	TranscriptFileFormatTxt TranscriptFileFormat = "txt"
)

func NewTranscriptFileFormatFromString(s string) (TranscriptFileFormat, error) {
	switch s {
	case "srt":
		return TranscriptFileFormatSrt, nil
	case "vtt":
		return TranscriptFileFormatVtt, nil
	case "txt":
		return TranscriptFileFormatTxt, nil
	}
	var t TranscriptFileFormat
	return "", fmt.Errorf("%s is not a valid %T", s, t)
}

func (t TranscriptFileFormat) Ptr() *TranscriptFileFormat {
	return &t
}

type VideoOutputTypeWithoutAvi string

const (
	VideoOutputTypeWithoutAviMkv VideoOutputTypeWithoutAvi = "mkv"
	VideoOutputTypeWithoutAviMp4 VideoOutputTypeWithoutAvi = "mp4"
	VideoOutputTypeWithoutAviMov VideoOutputTypeWithoutAvi = "mov"
	VideoOutputTypeWithoutAviMxf VideoOutputTypeWithoutAvi = "mxf"
)

func NewVideoOutputTypeWithoutAviFromString(s string) (VideoOutputTypeWithoutAvi, error) {
	switch s {
	case "mkv":
		return VideoOutputTypeWithoutAviMkv, nil
	case "mp4":
		return VideoOutputTypeWithoutAviMp4, nil
	case "mov":
		return VideoOutputTypeWithoutAviMov, nil
	case "mxf":
		return VideoOutputTypeWithoutAviMxf, nil
	}
	var t VideoOutputTypeWithoutAvi
	return "", fmt.Errorf("%s is not a valid %T", s, t)
}

func (v VideoOutputTypeWithoutAvi) Ptr() *VideoOutputTypeWithoutAvi {
	return &v
}

type DubbedOutputInAltFormatRequestPayloadOutputFormat struct {
	AudioOutputType           AudioOutputType
	VideoOutputTypeWithoutAvi VideoOutputTypeWithoutAvi

	typ string
}

func NewDubbedOutputInAltFormatRequestPayloadOutputFormatFromAudioOutputType(value AudioOutputType) *DubbedOutputInAltFormatRequestPayloadOutputFormat {
	return &DubbedOutputInAltFormatRequestPayloadOutputFormat{typ: "AudioOutputType", AudioOutputType: value}
}

func NewDubbedOutputInAltFormatRequestPayloadOutputFormatFromVideoOutputTypeWithoutAvi(value VideoOutputTypeWithoutAvi) *DubbedOutputInAltFormatRequestPayloadOutputFormat {
	return &DubbedOutputInAltFormatRequestPayloadOutputFormat{typ: "VideoOutputTypeWithoutAvi", VideoOutputTypeWithoutAvi: value}
}

func (d *DubbedOutputInAltFormatRequestPayloadOutputFormat) GetAudioOutputType() AudioOutputType {
	if d == nil {
		return ""
	}
	return d.AudioOutputType
}

func (d *DubbedOutputInAltFormatRequestPayloadOutputFormat) GetVideoOutputTypeWithoutAvi() VideoOutputTypeWithoutAvi {
	if d == nil {
		return ""
	}
	return d.VideoOutputTypeWithoutAvi
}

func (d *DubbedOutputInAltFormatRequestPayloadOutputFormat) UnmarshalJSON(data []byte) error {
	var valueAudioOutputType AudioOutputType
	if err := json.Unmarshal(data, &valueAudioOutputType); err == nil {
		d.typ = "AudioOutputType"
		d.AudioOutputType = valueAudioOutputType
		return nil
	}
	var valueVideoOutputTypeWithoutAvi VideoOutputTypeWithoutAvi
	if err := json.Unmarshal(data, &valueVideoOutputTypeWithoutAvi); err == nil {
		d.typ = "VideoOutputTypeWithoutAvi"
		d.VideoOutputTypeWithoutAvi = valueVideoOutputTypeWithoutAvi
		return nil
	}
	return fmt.Errorf("%s cannot be deserialized as a %T", data, d)
}

func (d DubbedOutputInAltFormatRequestPayloadOutputFormat) MarshalJSON() ([]byte, error) {
	if d.typ == "AudioOutputType" || d.AudioOutputType != "" {
		return json.Marshal(d.AudioOutputType)
	}
	if d.typ == "VideoOutputTypeWithoutAvi" || d.VideoOutputTypeWithoutAvi != "" {
		return json.Marshal(d.VideoOutputTypeWithoutAvi)
	}
	return nil, fmt.Errorf("type %T does not include a non-empty union type", d)
}

type DubbedOutputInAltFormatRequestPayloadOutputFormatVisitor interface {
	VisitAudioOutputType(AudioOutputType) error
	VisitVideoOutputTypeWithoutAvi(VideoOutputTypeWithoutAvi) error
}

func (d *DubbedOutputInAltFormatRequestPayloadOutputFormat) Accept(visitor DubbedOutputInAltFormatRequestPayloadOutputFormatVisitor) error {
	if d.typ == "AudioOutputType" || d.AudioOutputType != "" {
		return visitor.VisitAudioOutputType(d.AudioOutputType)
	}
	if d.typ == "VideoOutputTypeWithoutAvi" || d.VideoOutputTypeWithoutAvi != "" {
		return visitor.VisitVideoOutputTypeWithoutAvi(d.VideoOutputTypeWithoutAvi)
	}
	return fmt.Errorf("type %T does not include a non-empty union type", d)
}

type GetDubbedOutputInAltFormatDubAltFormatRunIDLanguagePostResponse struct {
	StringStringMap                map[string]string
	OrchestratorPipelineCallResult *OrchestratorPipelineCallResult

	typ string
}

func NewGetDubbedOutputInAltFormatDubAltFormatRunIDLanguagePostResponseFromStringStringMap(value map[string]string) *GetDubbedOutputInAltFormatDubAltFormatRunIDLanguagePostResponse {
	return &GetDubbedOutputInAltFormatDubAltFormatRunIDLanguagePostResponse{typ: "StringStringMap", StringStringMap: value}
}

func NewGetDubbedOutputInAltFormatDubAltFormatRunIDLanguagePostResponseFromOrchestratorPipelineCallResult(value *OrchestratorPipelineCallResult) *GetDubbedOutputInAltFormatDubAltFormatRunIDLanguagePostResponse {
	return &GetDubbedOutputInAltFormatDubAltFormatRunIDLanguagePostResponse{typ: "OrchestratorPipelineCallResult", OrchestratorPipelineCallResult: value}
}

func (g *GetDubbedOutputInAltFormatDubAltFormatRunIDLanguagePostResponse) GetStringStringMap() map[string]string {
	if g == nil {
		return nil
	}
	return g.StringStringMap
}

func (g *GetDubbedOutputInAltFormatDubAltFormatRunIDLanguagePostResponse) GetOrchestratorPipelineCallResult() *OrchestratorPipelineCallResult {
	if g == nil {
		return nil
	}
	return g.OrchestratorPipelineCallResult
}

func (g *GetDubbedOutputInAltFormatDubAltFormatRunIDLanguagePostResponse) UnmarshalJSON(data []byte) error {
	var valueStringStringMap map[string]string
	if err := json.Unmarshal(data, &valueStringStringMap); err == nil {
		g.typ = "StringStringMap"
		g.StringStringMap = valueStringStringMap
		return nil
	}
	valueOrchestratorPipelineCallResult := new(OrchestratorPipelineCallResult)
	if err := json.Unmarshal(data, &valueOrchestratorPipelineCallResult); err == nil {
		g.typ = "OrchestratorPipelineCallResult"
		g.OrchestratorPipelineCallResult = valueOrchestratorPipelineCallResult
		return nil
	}
	return fmt.Errorf("%s cannot be deserialized as a %T", data, g)
}

func (g GetDubbedOutputInAltFormatDubAltFormatRunIDLanguagePostResponse) MarshalJSON() ([]byte, error) {
	if g.typ == "StringStringMap" || g.StringStringMap != nil {
		return json.Marshal(g.StringStringMap)
	}
	if g.typ == "OrchestratorPipelineCallResult" || g.OrchestratorPipelineCallResult != nil {
		return json.Marshal(g.OrchestratorPipelineCallResult)
	}
	return nil, fmt.Errorf("type %T does not include a non-empty union type", g)
}

type GetDubbedOutputInAltFormatDubAltFormatRunIDLanguagePostResponseVisitor interface {
	VisitStringStringMap(map[string]string) error
	VisitOrchestratorPipelineCallResult(*OrchestratorPipelineCallResult) error
}

func (g *GetDubbedOutputInAltFormatDubAltFormatRunIDLanguagePostResponse) Accept(visitor GetDubbedOutputInAltFormatDubAltFormatRunIDLanguagePostResponseVisitor) error {
	if g.typ == "StringStringMap" || g.StringStringMap != nil {
		return visitor.VisitStringStringMap(g.StringStringMap)
	}
	if g.typ == "OrchestratorPipelineCallResult" || g.OrchestratorPipelineCallResult != nil {
		return visitor.VisitOrchestratorPipelineCallResult(g.OrchestratorPipelineCallResult)
	}
	return fmt.Errorf("type %T does not include a non-empty union type", g)
}

type GetDubbedRunInfoDubResultRunIDGetResponse struct {
	DubbingResult          *DubbingResult
	StringDubbingResultMap map[string]*DubbingResult

	typ string
}

func NewGetDubbedRunInfoDubResultRunIDGetResponseFromDubbingResult(value *DubbingResult) *GetDubbedRunInfoDubResultRunIDGetResponse {
	return &GetDubbedRunInfoDubResultRunIDGetResponse{typ: "DubbingResult", DubbingResult: value}
}

func NewGetDubbedRunInfoDubResultRunIDGetResponseFromStringDubbingResultMap(value map[string]*DubbingResult) *GetDubbedRunInfoDubResultRunIDGetResponse {
	return &GetDubbedRunInfoDubResultRunIDGetResponse{typ: "StringDubbingResultMap", StringDubbingResultMap: value}
}

func (g *GetDubbedRunInfoDubResultRunIDGetResponse) GetDubbingResult() *DubbingResult {
	if g == nil {
		return nil
	}
	return g.DubbingResult
}

func (g *GetDubbedRunInfoDubResultRunIDGetResponse) GetStringDubbingResultMap() map[string]*DubbingResult {
	if g == nil {
		return nil
	}
	return g.StringDubbingResultMap
}

func (g *GetDubbedRunInfoDubResultRunIDGetResponse) UnmarshalJSON(data []byte) error {
	valueDubbingResult := new(DubbingResult)
	if err := json.Unmarshal(data, &valueDubbingResult); err == nil {
		g.typ = "DubbingResult"
		g.DubbingResult = valueDubbingResult
		return nil
	}
	var valueStringDubbingResultMap map[string]*DubbingResult
	if err := json.Unmarshal(data, &valueStringDubbingResultMap); err == nil {
		g.typ = "StringDubbingResultMap"
		g.StringDubbingResultMap = valueStringDubbingResultMap
		return nil
	}
	return fmt.Errorf("%s cannot be deserialized as a %T", data, g)
}

func (g GetDubbedRunInfoDubResultRunIDGetResponse) MarshalJSON() ([]byte, error) {
	if g.typ == "DubbingResult" || g.DubbingResult != nil {
		return json.Marshal(g.DubbingResult)
	}
	if g.typ == "StringDubbingResultMap" || g.StringDubbingResultMap != nil {
		return json.Marshal(g.StringDubbingResultMap)
	}
	return nil, fmt.Errorf("type %T does not include a non-empty union type", g)
}

type GetDubbedRunInfoDubResultRunIDGetResponseVisitor interface {
	VisitDubbingResult(*DubbingResult) error
	VisitStringDubbingResultMap(map[string]*DubbingResult) error
}

func (g *GetDubbedRunInfoDubResultRunIDGetResponse) Accept(visitor GetDubbedRunInfoDubResultRunIDGetResponseVisitor) error {
	if g.typ == "DubbingResult" || g.DubbingResult != nil {
		return visitor.VisitDubbingResult(g.DubbingResult)
	}
	if g.typ == "StringDubbingResultMap" || g.StringDubbingResultMap != nil {
		return visitor.VisitStringDubbingResultMap(g.StringDubbingResultMap)
	}
	return fmt.Errorf("type %T does not include a non-empty union type", g)
}

type GetDubbingRunsResultsDubbingResultsPostResponseValue struct {
	DubbingResult          *DubbingResult
	StringDubbingResultMap map[string]*DubbingResult

	typ string
}

func NewGetDubbingRunsResultsDubbingResultsPostResponseValueFromDubbingResult(value *DubbingResult) *GetDubbingRunsResultsDubbingResultsPostResponseValue {
	return &GetDubbingRunsResultsDubbingResultsPostResponseValue{typ: "DubbingResult", DubbingResult: value}
}

func NewGetDubbingRunsResultsDubbingResultsPostResponseValueFromStringDubbingResultMap(value map[string]*DubbingResult) *GetDubbingRunsResultsDubbingResultsPostResponseValue {
	return &GetDubbingRunsResultsDubbingResultsPostResponseValue{typ: "StringDubbingResultMap", StringDubbingResultMap: value}
}

func (g *GetDubbingRunsResultsDubbingResultsPostResponseValue) GetDubbingResult() *DubbingResult {
	if g == nil {
		return nil
	}
	return g.DubbingResult
}

func (g *GetDubbingRunsResultsDubbingResultsPostResponseValue) GetStringDubbingResultMap() map[string]*DubbingResult {
	if g == nil {
		return nil
	}
	return g.StringDubbingResultMap
}

func (g *GetDubbingRunsResultsDubbingResultsPostResponseValue) UnmarshalJSON(data []byte) error {
	valueDubbingResult := new(DubbingResult)
	if err := json.Unmarshal(data, &valueDubbingResult); err == nil {
		g.typ = "DubbingResult"
		g.DubbingResult = valueDubbingResult
		return nil
	}
	var valueStringDubbingResultMap map[string]*DubbingResult
	if err := json.Unmarshal(data, &valueStringDubbingResultMap); err == nil {
		g.typ = "StringDubbingResultMap"
		g.StringDubbingResultMap = valueStringDubbingResultMap
		return nil
	}
	return fmt.Errorf("%s cannot be deserialized as a %T", data, g)
}

func (g GetDubbingRunsResultsDubbingResultsPostResponseValue) MarshalJSON() ([]byte, error) {
	if g.typ == "DubbingResult" || g.DubbingResult != nil {
		return json.Marshal(g.DubbingResult)
	}
	if g.typ == "StringDubbingResultMap" || g.StringDubbingResultMap != nil {
		return json.Marshal(g.StringDubbingResultMap)
	}
	return nil, fmt.Errorf("type %T does not include a non-empty union type", g)
}

type GetDubbingRunsResultsDubbingResultsPostResponseValueVisitor interface {
	VisitDubbingResult(*DubbingResult) error
	VisitStringDubbingResultMap(map[string]*DubbingResult) error
}

func (g *GetDubbingRunsResultsDubbingResultsPostResponseValue) Accept(visitor GetDubbingRunsResultsDubbingResultsPostResponseValueVisitor) error {
	if g.typ == "DubbingResult" || g.DubbingResult != nil {
		return visitor.VisitDubbingResult(g.DubbingResult)
	}
	if g.typ == "StringDubbingResultMap" || g.StringDubbingResultMap != nil {
		return visitor.VisitStringDubbingResultMap(g.StringDubbingResultMap)
	}
	return fmt.Errorf("type %T does not include a non-empty union type", g)
}
