// This file was auto-generated by Fern from our API Definition.

package api

import (
	json "encoding/json"
	fmt "fmt"
	core "sdk/core"
)

type CreateFolderPayload struct {
	RunID      *int   `json:"-" url:"run_id,omitempty"`
	FolderName string `json:"folder_name" url:"-"`
}

type ListFoldersFoldersGetRequest struct {
	Limit       *int    `json:"-" url:"limit,omitempty"`
	SearchQuery *string `json:"-" url:"search_query,omitempty"`
	RunID       *int    `json:"-" url:"run_id,omitempty"`
}

type Folder struct {
	TeamID int    `json:"team_id" url:"team_id"`
	Name   string `json:"name" url:"name"`

	extraProperties map[string]interface{}
	_rawJSON        json.RawMessage
}

func (f *Folder) GetTeamID() int {
	if f == nil {
		return 0
	}
	return f.TeamID
}

func (f *Folder) GetName() string {
	if f == nil {
		return ""
	}
	return f.Name
}

func (f *Folder) GetExtraProperties() map[string]interface{} {
	return f.extraProperties
}

func (f *Folder) UnmarshalJSON(data []byte) error {
	type unmarshaler Folder
	var value unmarshaler
	if err := json.Unmarshal(data, &value); err != nil {
		return err
	}
	*f = Folder(value)

	extraProperties, err := core.ExtractExtraProperties(data, *f)
	if err != nil {
		return err
	}
	f.extraProperties = extraProperties

	f._rawJSON = json.RawMessage(data)
	return nil
}

func (f *Folder) String() string {
	if len(f._rawJSON) > 0 {
		if value, err := core.StringifyJSON(f._rawJSON); err == nil {
			return value
		}
	}
	if value, err := core.StringifyJSON(f); err == nil {
		return value
	}
	return fmt.Sprintf("%#v", f)
}
