// This file was auto-generated by Fern from our API Definition.

package api

import (
	json "encoding/json"
	fmt "fmt"
	core "sdk/core"
)

type GetSourceLanguagesSourceLanguagesGetRequest struct {
	RunID *int `json:"-" url:"run_id,omitempty"`
}

type GetTargetLanguagesTargetLanguagesGetRequest struct {
	RunID *int `json:"-" url:"run_id,omitempty"`
}

type LanguagePydanticModel struct {
	ID        int    `json:"id" url:"id"`
	Language  string `json:"language" url:"language"`
	ShortName string `json:"short_name" url:"short_name"`

	extraProperties map[string]interface{}
	_rawJSON        json.RawMessage
}

func (l *LanguagePydanticModel) GetID() int {
	if l == nil {
		return 0
	}
	return l.ID
}

func (l *LanguagePydanticModel) GetLanguage() string {
	if l == nil {
		return ""
	}
	return l.Language
}

func (l *LanguagePydanticModel) GetShortName() string {
	if l == nil {
		return ""
	}
	return l.ShortName
}

func (l *LanguagePydanticModel) GetExtraProperties() map[string]interface{} {
	return l.extraProperties
}

func (l *LanguagePydanticModel) UnmarshalJSON(data []byte) error {
	type unmarshaler LanguagePydanticModel
	var value unmarshaler
	if err := json.Unmarshal(data, &value); err != nil {
		return err
	}
	*l = LanguagePydanticModel(value)

	extraProperties, err := core.ExtractExtraProperties(data, *l)
	if err != nil {
		return err
	}
	l.extraProperties = extraProperties

	l._rawJSON = json.RawMessage(data)
	return nil
}

func (l *LanguagePydanticModel) String() string {
	if len(l._rawJSON) > 0 {
		if value, err := core.StringifyJSON(l._rawJSON); err == nil {
			return value
		}
	}
	if value, err := core.StringifyJSON(l); err == nil {
		return value
	}
	return fmt.Sprintf("%#v", l)
}
