// This file was auto-generated by Fern from our API Definition.

package api

import (
	json "encoding/json"
	fmt "fmt"
	core "sdk/core"
	time "time"
)

type CreateProjectSetupRequestPayload struct {
	RunID                   *int        `json:"-" url:"run_id,omitempty"`
	ProjectName             *string     `json:"project_name,omitempty" url:"-"`
	ProjectDescription      *string     `json:"project_description,omitempty" url:"-"`
	FolderID                *int        `json:"folder_id,omitempty" url:"-"`
	MediaURL                string      `json:"media_url" url:"-"`
	SourceLanguage          Languages   `json:"source_language" url:"-"`
	TargetLanguages         []Languages `json:"target_languages,omitempty" url:"-"`
	SelectedAudioTracks     []int       `json:"selected_audio_tracks,omitempty" url:"-"`
	AddOutputAsAnAudioTrack *bool       `json:"add_output_as_an_audio_track,omitempty" url:"-"`
	ChosenDictionaries      []int       `json:"chosen_dictionaries,omitempty" url:"-"`
}

type CreateProjectSetupTaskStatusProjectSetupTaskIDGetRequest struct {
	RunID *int `json:"-" url:"run_id,omitempty"`
}

type GetProjectSetupResultProjectSetupResultRunIDGetRequest struct {
}

type GetProjectSetupRunsResultsProjectSetupResultsPostRequest struct {
	RunID *int                  `json:"-" url:"run_id,omitempty"`
	Body  *RunIDsRequestPayload `json:"-" url:"-"`
}

func (g *GetProjectSetupRunsResultsProjectSetupResultsPostRequest) UnmarshalJSON(data []byte) error {
	body := new(RunIDsRequestPayload)
	if err := json.Unmarshal(data, &body); err != nil {
		return err
	}
	g.Body = body
	return nil
}

func (g *GetProjectSetupRunsResultsProjectSetupResultsPostRequest) MarshalJSON() ([]byte, error) {
	return json.Marshal(g.Body)
}

type CreateProjectSetupOut struct {
	TaskID string `json:"task_id" url:"task_id"`

	extraProperties map[string]interface{}
	_rawJSON        json.RawMessage
}

func (c *CreateProjectSetupOut) GetTaskID() string {
	if c == nil {
		return ""
	}
	return c.TaskID
}

func (c *CreateProjectSetupOut) GetExtraProperties() map[string]interface{} {
	return c.extraProperties
}

func (c *CreateProjectSetupOut) UnmarshalJSON(data []byte) error {
	type unmarshaler CreateProjectSetupOut
	var value unmarshaler
	if err := json.Unmarshal(data, &value); err != nil {
		return err
	}
	*c = CreateProjectSetupOut(value)

	extraProperties, err := core.ExtractExtraProperties(data, *c)
	if err != nil {
		return err
	}
	c.extraProperties = extraProperties

	c._rawJSON = json.RawMessage(data)
	return nil
}

func (c *CreateProjectSetupOut) String() string {
	if len(c._rawJSON) > 0 {
		if value, err := core.StringifyJSON(c._rawJSON); err == nil {
			return value
		}
	}
	if value, err := core.StringifyJSON(c); err == nil {
		return value
	}
	return fmt.Sprintf("%#v", c)
}

type GetCreateProjectSetupResponse struct {
	RunID          int             `json:"run_id" url:"run_id"`
	ProjectDetails *ProjectDetails `json:"project_details,omitempty" url:"project_details,omitempty"`

	extraProperties map[string]interface{}
	_rawJSON        json.RawMessage
}

func (g *GetCreateProjectSetupResponse) GetRunID() int {
	if g == nil {
		return 0
	}
	return g.RunID
}

func (g *GetCreateProjectSetupResponse) GetProjectDetails() *ProjectDetails {
	if g == nil {
		return nil
	}
	return g.ProjectDetails
}

func (g *GetCreateProjectSetupResponse) GetExtraProperties() map[string]interface{} {
	return g.extraProperties
}

func (g *GetCreateProjectSetupResponse) UnmarshalJSON(data []byte) error {
	type unmarshaler GetCreateProjectSetupResponse
	var value unmarshaler
	if err := json.Unmarshal(data, &value); err != nil {
		return err
	}
	*g = GetCreateProjectSetupResponse(value)

	extraProperties, err := core.ExtractExtraProperties(data, *g)
	if err != nil {
		return err
	}
	g.extraProperties = extraProperties

	g._rawJSON = json.RawMessage(data)
	return nil
}

func (g *GetCreateProjectSetupResponse) String() string {
	if len(g._rawJSON) > 0 {
		if value, err := core.StringifyJSON(g._rawJSON); err == nil {
			return value
		}
	}
	if value, err := core.StringifyJSON(g); err == nil {
		return value
	}
	return fmt.Sprintf("%#v", g)
}

type ProjectDetails struct {
	ProjectName        string      `json:"project_name" url:"project_name"`
	ProjectDescription *string     `json:"project_description,omitempty" url:"project_description,omitempty"`
	CreatedAt          time.Time   `json:"created_at" url:"created_at"`
	SourceLanguage     Languages   `json:"source_language" url:"source_language"`
	TargetLanguages    []Languages `json:"target_languages,omitempty" url:"target_languages,omitempty"`
	Duration           *float64    `json:"duration,omitempty" url:"duration,omitempty"`
	FolderID           *int        `json:"folder_id,omitempty" url:"folder_id,omitempty"`
	StudioURL          string      `json:"studio_url" url:"studio_url"`

	extraProperties map[string]interface{}
	_rawJSON        json.RawMessage
}

func (p *ProjectDetails) GetProjectName() string {
	if p == nil {
		return ""
	}
	return p.ProjectName
}

func (p *ProjectDetails) GetProjectDescription() *string {
	if p == nil {
		return nil
	}
	return p.ProjectDescription
}

func (p *ProjectDetails) GetCreatedAt() time.Time {
	if p == nil {
		return time.Time{}
	}
	return p.CreatedAt
}

func (p *ProjectDetails) GetSourceLanguage() Languages {
	if p == nil {
		return 0
	}
	return p.SourceLanguage
}

func (p *ProjectDetails) GetTargetLanguages() []Languages {
	if p == nil {
		return nil
	}
	return p.TargetLanguages
}

func (p *ProjectDetails) GetDuration() *float64 {
	if p == nil {
		return nil
	}
	return p.Duration
}

func (p *ProjectDetails) GetFolderID() *int {
	if p == nil {
		return nil
	}
	return p.FolderID
}

func (p *ProjectDetails) GetStudioURL() string {
	if p == nil {
		return ""
	}
	return p.StudioURL
}

func (p *ProjectDetails) GetExtraProperties() map[string]interface{} {
	return p.extraProperties
}

func (p *ProjectDetails) UnmarshalJSON(data []byte) error {
	type embed ProjectDetails
	var unmarshaler = struct {
		embed
		CreatedAt *core.DateTime `json:"created_at"`
	}{
		embed: embed(*p),
	}
	if err := json.Unmarshal(data, &unmarshaler); err != nil {
		return err
	}
	*p = ProjectDetails(unmarshaler.embed)
	p.CreatedAt = unmarshaler.CreatedAt.Time()

	extraProperties, err := core.ExtractExtraProperties(data, *p)
	if err != nil {
		return err
	}
	p.extraProperties = extraProperties

	p._rawJSON = json.RawMessage(data)
	return nil
}

func (p *ProjectDetails) MarshalJSON() ([]byte, error) {
	type embed ProjectDetails
	var marshaler = struct {
		embed
		CreatedAt *core.DateTime `json:"created_at"`
	}{
		embed:     embed(*p),
		CreatedAt: core.NewDateTime(p.CreatedAt),
	}
	return json.Marshal(marshaler)
}

func (p *ProjectDetails) String() string {
	if len(p._rawJSON) > 0 {
		if value, err := core.StringifyJSON(p._rawJSON); err == nil {
			return value
		}
	}
	if value, err := core.StringifyJSON(p); err == nil {
		return value
	}
	return fmt.Sprintf("%#v", p)
}
