// This file was auto-generated by Fern from our API Definition.

package api

import (
	json "encoding/json"
	fmt "fmt"
	core "sdk/core"
	time "time"
)

type BodyCreateStoryStoryPost struct {
	RunID              *int      `json:"-" url:"run_id,omitempty"`
	SourceLanguage     Languages `json:"source_language" url:"-"`
	Title              *string   `json:"title,omitempty" url:"-"`
	Description        *string   `json:"description,omitempty" url:"-"`
	NarratorVoiceID    *int      `json:"narrator_voice_id,omitempty" url:"-"`
	FolderID           *int      `json:"folder_id,omitempty" url:"-"`
	ChosenDictionaries []int     `json:"chosen_dictionaries,omitempty" url:"-"`
}

type GetStoriesRunsResultsStoriesResultsPostRequest struct {
	Traceparent *string               `json:"-" url:"-"`
	RunID       *int                  `json:"-" url:"run_id,omitempty"`
	Body        *RunIDsRequestPayload `json:"-" url:"-"`
}

func (g *GetStoriesRunsResultsStoriesResultsPostRequest) UnmarshalJSON(data []byte) error {
	body := new(RunIDsRequestPayload)
	if err := json.Unmarshal(data, &body); err != nil {
		return err
	}
	g.Body = body
	return nil
}

func (g *GetStoriesRunsResultsStoriesResultsPostRequest) MarshalJSON() ([]byte, error) {
	return json.Marshal(g.Body)
}

type GetStoryRunInfoStoryResultRunIDGetRequest struct {
	// Whether to include the transcription in the response for fetching the result of a Stories run.
	IncludeTranscript *bool `json:"-" url:"include_transcript,omitempty"`
}

type GetStoryStatusStoryTaskIDGetRequest struct {
	RunID *int `json:"-" url:"run_id,omitempty"`
}

type BodySetupStoryStorySetupPost struct {
	RunID              *int      `json:"-" url:"run_id,omitempty"`
	SourceLanguage     Languages `json:"source_language" url:"-"`
	Title              *string   `json:"title,omitempty" url:"-"`
	Description        *string   `json:"description,omitempty" url:"-"`
	NarratorVoiceID    *int      `json:"narrator_voice_id,omitempty" url:"-"`
	FolderID           *int      `json:"folder_id,omitempty" url:"-"`
	ChosenDictionaries []int     `json:"chosen_dictionaries,omitempty" url:"-"`
}

type GetSetupStoryResultResponse struct {
	RunID        int           `json:"run_id" url:"run_id"`
	StoryDetails *StoryDetails `json:"story_details,omitempty" url:"story_details,omitempty"`

	extraProperties map[string]interface{}
	_rawJSON        json.RawMessage
}

func (g *GetSetupStoryResultResponse) GetRunID() int {
	if g == nil {
		return 0
	}
	return g.RunID
}

func (g *GetSetupStoryResultResponse) GetStoryDetails() *StoryDetails {
	if g == nil {
		return nil
	}
	return g.StoryDetails
}

func (g *GetSetupStoryResultResponse) GetExtraProperties() map[string]interface{} {
	return g.extraProperties
}

func (g *GetSetupStoryResultResponse) UnmarshalJSON(data []byte) error {
	type unmarshaler GetSetupStoryResultResponse
	var value unmarshaler
	if err := json.Unmarshal(data, &value); err != nil {
		return err
	}
	*g = GetSetupStoryResultResponse(value)

	extraProperties, err := core.ExtractExtraProperties(data, *g)
	if err != nil {
		return err
	}
	g.extraProperties = extraProperties

	g._rawJSON = json.RawMessage(data)
	return nil
}

func (g *GetSetupStoryResultResponse) String() string {
	if len(g._rawJSON) > 0 {
		if value, err := core.StringifyJSON(g._rawJSON); err == nil {
			return value
		}
	}
	if value, err := core.StringifyJSON(g); err == nil {
		return value
	}
	return fmt.Sprintf("%#v", g)
}

type StoryDetails struct {
	StoryTitle       string      `json:"story_title" url:"story_title"`
	StoryDescription *string     `json:"story_description,omitempty" url:"story_description,omitempty"`
	CreatedAt        time.Time   `json:"created_at" url:"created_at"`
	SourceLanguage   Languages   `json:"source_language" url:"source_language"`
	TargetLanguages  []Languages `json:"target_languages,omitempty" url:"target_languages,omitempty"`
	FolderID         *int        `json:"folder_id,omitempty" url:"folder_id,omitempty"`
	StudioURL        string      `json:"studio_url" url:"studio_url"`

	extraProperties map[string]interface{}
	_rawJSON        json.RawMessage
}

func (s *StoryDetails) GetStoryTitle() string {
	if s == nil {
		return ""
	}
	return s.StoryTitle
}

func (s *StoryDetails) GetStoryDescription() *string {
	if s == nil {
		return nil
	}
	return s.StoryDescription
}

func (s *StoryDetails) GetCreatedAt() time.Time {
	if s == nil {
		return time.Time{}
	}
	return s.CreatedAt
}

func (s *StoryDetails) GetSourceLanguage() Languages {
	if s == nil {
		return 0
	}
	return s.SourceLanguage
}

func (s *StoryDetails) GetTargetLanguages() []Languages {
	if s == nil {
		return nil
	}
	return s.TargetLanguages
}

func (s *StoryDetails) GetFolderID() *int {
	if s == nil {
		return nil
	}
	return s.FolderID
}

func (s *StoryDetails) GetStudioURL() string {
	if s == nil {
		return ""
	}
	return s.StudioURL
}

func (s *StoryDetails) GetExtraProperties() map[string]interface{} {
	return s.extraProperties
}

func (s *StoryDetails) UnmarshalJSON(data []byte) error {
	type embed StoryDetails
	var unmarshaler = struct {
		embed
		CreatedAt *core.DateTime `json:"created_at"`
	}{
		embed: embed(*s),
	}
	if err := json.Unmarshal(data, &unmarshaler); err != nil {
		return err
	}
	*s = StoryDetails(unmarshaler.embed)
	s.CreatedAt = unmarshaler.CreatedAt.Time()

	extraProperties, err := core.ExtractExtraProperties(data, *s)
	if err != nil {
		return err
	}
	s.extraProperties = extraProperties

	s._rawJSON = json.RawMessage(data)
	return nil
}

func (s *StoryDetails) MarshalJSON() ([]byte, error) {
	type embed StoryDetails
	var marshaler = struct {
		embed
		CreatedAt *core.DateTime `json:"created_at"`
	}{
		embed:     embed(*s),
		CreatedAt: core.NewDateTime(s.CreatedAt),
	}
	return json.Marshal(marshaler)
}

func (s *StoryDetails) String() string {
	if len(s._rawJSON) > 0 {
		if value, err := core.StringifyJSON(s._rawJSON); err == nil {
			return value
		}
	}
	if value, err := core.StringifyJSON(s); err == nil {
		return value
	}
	return fmt.Sprintf("%#v", s)
}

type CreateStoryStoryPostResponse struct {
	OrchestratorPipelineCallResult *OrchestratorPipelineCallResult
	GetSetupStoryResultResponse    *GetSetupStoryResultResponse

	typ string
}

func NewCreateStoryStoryPostResponseFromOrchestratorPipelineCallResult(value *OrchestratorPipelineCallResult) *CreateStoryStoryPostResponse {
	return &CreateStoryStoryPostResponse{typ: "OrchestratorPipelineCallResult", OrchestratorPipelineCallResult: value}
}

func NewCreateStoryStoryPostResponseFromGetSetupStoryResultResponse(value *GetSetupStoryResultResponse) *CreateStoryStoryPostResponse {
	return &CreateStoryStoryPostResponse{typ: "GetSetupStoryResultResponse", GetSetupStoryResultResponse: value}
}

func (c *CreateStoryStoryPostResponse) GetOrchestratorPipelineCallResult() *OrchestratorPipelineCallResult {
	if c == nil {
		return nil
	}
	return c.OrchestratorPipelineCallResult
}

func (c *CreateStoryStoryPostResponse) GetGetSetupStoryResultResponse() *GetSetupStoryResultResponse {
	if c == nil {
		return nil
	}
	return c.GetSetupStoryResultResponse
}

func (c *CreateStoryStoryPostResponse) UnmarshalJSON(data []byte) error {
	valueOrchestratorPipelineCallResult := new(OrchestratorPipelineCallResult)
	if err := json.Unmarshal(data, &valueOrchestratorPipelineCallResult); err == nil {
		c.typ = "OrchestratorPipelineCallResult"
		c.OrchestratorPipelineCallResult = valueOrchestratorPipelineCallResult
		return nil
	}
	valueGetSetupStoryResultResponse := new(GetSetupStoryResultResponse)
	if err := json.Unmarshal(data, &valueGetSetupStoryResultResponse); err == nil {
		c.typ = "GetSetupStoryResultResponse"
		c.GetSetupStoryResultResponse = valueGetSetupStoryResultResponse
		return nil
	}
	return fmt.Errorf("%s cannot be deserialized as a %T", data, c)
}

func (c CreateStoryStoryPostResponse) MarshalJSON() ([]byte, error) {
	if c.typ == "OrchestratorPipelineCallResult" || c.OrchestratorPipelineCallResult != nil {
		return json.Marshal(c.OrchestratorPipelineCallResult)
	}
	if c.typ == "GetSetupStoryResultResponse" || c.GetSetupStoryResultResponse != nil {
		return json.Marshal(c.GetSetupStoryResultResponse)
	}
	return nil, fmt.Errorf("type %T does not include a non-empty union type", c)
}

type CreateStoryStoryPostResponseVisitor interface {
	VisitOrchestratorPipelineCallResult(*OrchestratorPipelineCallResult) error
	VisitGetSetupStoryResultResponse(*GetSetupStoryResultResponse) error
}

func (c *CreateStoryStoryPostResponse) Accept(visitor CreateStoryStoryPostResponseVisitor) error {
	if c.typ == "OrchestratorPipelineCallResult" || c.OrchestratorPipelineCallResult != nil {
		return visitor.VisitOrchestratorPipelineCallResult(c.OrchestratorPipelineCallResult)
	}
	if c.typ == "GetSetupStoryResultResponse" || c.GetSetupStoryResultResponse != nil {
		return visitor.VisitGetSetupStoryResultResponse(c.GetSetupStoryResultResponse)
	}
	return fmt.Errorf("type %T does not include a non-empty union type", c)
}

type SetupStoryStorySetupPostResponse struct {
	OrchestratorPipelineCallResult *OrchestratorPipelineCallResult
	GetSetupStoryResultResponse    *GetSetupStoryResultResponse

	typ string
}

func NewSetupStoryStorySetupPostResponseFromOrchestratorPipelineCallResult(value *OrchestratorPipelineCallResult) *SetupStoryStorySetupPostResponse {
	return &SetupStoryStorySetupPostResponse{typ: "OrchestratorPipelineCallResult", OrchestratorPipelineCallResult: value}
}

func NewSetupStoryStorySetupPostResponseFromGetSetupStoryResultResponse(value *GetSetupStoryResultResponse) *SetupStoryStorySetupPostResponse {
	return &SetupStoryStorySetupPostResponse{typ: "GetSetupStoryResultResponse", GetSetupStoryResultResponse: value}
}

func (s *SetupStoryStorySetupPostResponse) GetOrchestratorPipelineCallResult() *OrchestratorPipelineCallResult {
	if s == nil {
		return nil
	}
	return s.OrchestratorPipelineCallResult
}

func (s *SetupStoryStorySetupPostResponse) GetGetSetupStoryResultResponse() *GetSetupStoryResultResponse {
	if s == nil {
		return nil
	}
	return s.GetSetupStoryResultResponse
}

func (s *SetupStoryStorySetupPostResponse) UnmarshalJSON(data []byte) error {
	valueOrchestratorPipelineCallResult := new(OrchestratorPipelineCallResult)
	if err := json.Unmarshal(data, &valueOrchestratorPipelineCallResult); err == nil {
		s.typ = "OrchestratorPipelineCallResult"
		s.OrchestratorPipelineCallResult = valueOrchestratorPipelineCallResult
		return nil
	}
	valueGetSetupStoryResultResponse := new(GetSetupStoryResultResponse)
	if err := json.Unmarshal(data, &valueGetSetupStoryResultResponse); err == nil {
		s.typ = "GetSetupStoryResultResponse"
		s.GetSetupStoryResultResponse = valueGetSetupStoryResultResponse
		return nil
	}
	return fmt.Errorf("%s cannot be deserialized as a %T", data, s)
}

func (s SetupStoryStorySetupPostResponse) MarshalJSON() ([]byte, error) {
	if s.typ == "OrchestratorPipelineCallResult" || s.OrchestratorPipelineCallResult != nil {
		return json.Marshal(s.OrchestratorPipelineCallResult)
	}
	if s.typ == "GetSetupStoryResultResponse" || s.GetSetupStoryResultResponse != nil {
		return json.Marshal(s.GetSetupStoryResultResponse)
	}
	return nil, fmt.Errorf("type %T does not include a non-empty union type", s)
}

type SetupStoryStorySetupPostResponseVisitor interface {
	VisitOrchestratorPipelineCallResult(*OrchestratorPipelineCallResult) error
	VisitGetSetupStoryResultResponse(*GetSetupStoryResultResponse) error
}

func (s *SetupStoryStorySetupPostResponse) Accept(visitor SetupStoryStorySetupPostResponseVisitor) error {
	if s.typ == "OrchestratorPipelineCallResult" || s.OrchestratorPipelineCallResult != nil {
		return visitor.VisitOrchestratorPipelineCallResult(s.OrchestratorPipelineCallResult)
	}
	if s.typ == "GetSetupStoryResultResponse" || s.GetSetupStoryResultResponse != nil {
		return visitor.VisitGetSetupStoryResultResponse(s.GetSetupStoryResultResponse)
	}
	return fmt.Errorf("type %T does not include a non-empty union type", s)
}
