// This file was auto-generated by Fern from our API Definition.

package api

import (
	json "encoding/json"
	core "sdk/core"
	time "time"
)

type DestroyStreamStreamStreamIDDeleteRequest struct {
	RunID *int `json:"-" url:"run_id,omitempty"`
}

type GetProbeStreamStreamProbePostRequest struct {
	RunID *int              `json:"-" url:"run_id,omitempty"`
	Body  *GetProbeStreamIn `json:"-" url:"-"`
}

func (g *GetProbeStreamStreamProbePostRequest) UnmarshalJSON(data []byte) error {
	body := new(GetProbeStreamIn)
	if err := json.Unmarshal(data, &body); err != nil {
		return err
	}
	g.Body = body
	return nil
}

func (g *GetProbeStreamStreamProbePostRequest) MarshalJSON() ([]byte, error) {
	return json.Marshal(g.Body)
}

type GetStreamResultStreamStreamIDGetRequest struct {
	RunID *int `json:"-" url:"run_id,omitempty"`
}

type UpdateStreamDataRequestPayload struct {
	RunID           *int                   `json:"-" url:"run_id,omitempty"`
	StartTime       *time.Time             `json:"start_time,omitempty" url:"-"`
	EndTime         *time.Time             `json:"end_time,omitempty" url:"-"`
	Payload         map[string]interface{} `json:"payload,omitempty" url:"-"`
	TargetLanguages []Languages            `json:"target_languages,omitempty" url:"-"`
	Timezone        *string                `json:"timezone,omitempty" url:"-"`
}

func (u *UpdateStreamDataRequestPayload) UnmarshalJSON(data []byte) error {
	type unmarshaler UpdateStreamDataRequestPayload
	var body unmarshaler
	if err := json.Unmarshal(data, &body); err != nil {
		return err
	}
	*u = UpdateStreamDataRequestPayload(body)
	return nil
}

func (u *UpdateStreamDataRequestPayload) MarshalJSON() ([]byte, error) {
	type embed UpdateStreamDataRequestPayload
	var marshaler = struct {
		embed
		StartTime *core.DateTime `json:"start_time,omitempty"`
		EndTime   *core.DateTime `json:"end_time,omitempty"`
	}{
		embed:     embed(*u),
		StartTime: core.NewOptionalDateTime(u.StartTime),
		EndTime:   core.NewOptionalDateTime(u.EndTime),
	}
	return json.Marshal(marshaler)
}
