// This file was auto-generated by Fern from our API Definition.

package cambai

import (
	json "encoding/json"
	fmt "fmt"

	core "github.com/camb-ai/cambai-go-sdk/core"
)

type CreateTtsRequestPayload struct {
	RunID              *int      `json:"-" url:"run_id,omitempty"`
	ProjectName        *string   `json:"project_name,omitempty" url:"project_name,omitempty"`
	ProjectDescription *string   `json:"project_description,omitempty" url:"project_description,omitempty"`
	FolderID           *int      `json:"folder_id,omitempty" url:"folder_id,omitempty"`
	Text               string    `json:"text" url:"text"`
	VoiceID            int       `json:"voice_id" url:"voice_id"`
	Language           Languages `json:"language" url:"language"`
	Gender             *Gender   `json:"gender,omitempty" url:"gender,omitempty"`
	Age                *int      `json:"age,omitempty" url:"age,omitempty"`
}

type GetTtsResultTtsTaskIDGetRequest struct {
	RunID *int `json:"-" url:"run_id,omitempty"`
}

type GetTtsResultDiscordDiscordTtsTaskIDGetRequest struct {
	RunID *int `json:"-" url:"run_id,omitempty"`
}

type GetTtsResultsTtsResultsPostRequest struct {
	Traceparent *string               `json:"-" url:"-"`
	RunID       *int                  `json:"-" url:"run_id,omitempty"`
	Body        *RunIDsRequestPayload `json:"-" url:"-"`
}

func (g *GetTtsResultsTtsResultsPostRequest) UnmarshalJSON(data []byte) error {
	body := new(RunIDsRequestPayload)
	if err := json.Unmarshal(data, &body); err != nil {
		return err
	}
	g.Body = body
	return nil
}

func (g *GetTtsResultsTtsResultsPostRequest) MarshalJSON() ([]byte, error) {
	return json.Marshal(g.Body)
}

type GetTtsRunInfoTtsResultRunIDGetRequest struct {
	// Output format for the Text To Speech result
	OutputType *string `json:"-" url:"output_type,omitempty"`
}

type CreateStreamTtsRequestPayload struct {
	Text                              string                                    `json:"text" url:"text"`
	Language                          TtsLanguage     `json:"language,omitempty" url:"language,omitempty"`
	VoiceID                           int                                       `json:"voice_id" url:"voice_id"`
	SpeechModel                       *SpeechModel `json:"speech_model,omitempty" url:"speech_model,omitempty"`
	UserInstructions                  *string                                   `json:"user_instructions,omitempty" url:"user_instructions,omitempty"`
	EnhanceNamedEntitiesPronunciation *bool                                     `json:"enhance_named_entities_pronunciation,omitempty" url:"enhance_named_entities_pronunciation,omitempty"`
	OutputConfiguration               *StreamTtsOutputConfiguration             `json:"output_configuration,omitempty" url:"output_configuration,omitempty"`
	VoiceSettings                     *StreamTtsVoiceSettings                   `json:"voice_settings,omitempty" url:"voice_settings,omitempty"`
	InferenceOptions                  *StreamTtsInferenceOptions                `json:"inference_options,omitempty" url:"inference_options,omitempty"`
}

type CreateTtsOut struct {
	TaskID string `json:"task_id" url:"task_id"`

	_rawJSON json.RawMessage
}

func (c *CreateTtsOut) UnmarshalJSON(data []byte) error {
	type unmarshaler CreateTtsOut
	var value unmarshaler
	if err := json.Unmarshal(data, &value); err != nil {
		return err
	}
	*c = CreateTtsOut(value)
	c._rawJSON = json.RawMessage(data)
	return nil
}

func (c *CreateTtsOut) String() string {
	if len(c._rawJSON) > 0 {
		if value, err := core.StringifyJSON(c._rawJSON); err == nil {
			return value
		}
	}
	if value, err := core.StringifyJSON(c); err == nil {
		return value
	}
	return fmt.Sprintf("%#v", c)
}

type GetTtsResultOutFileURL struct {
	OutputURL string `json:"output_url" url:"output_url"`

	_rawJSON json.RawMessage
}

func (g *GetTtsResultOutFileURL) UnmarshalJSON(data []byte) error {
	type unmarshaler GetTtsResultOutFileURL
	var value unmarshaler
	if err := json.Unmarshal(data, &value); err != nil {
		return err
	}
	*g = GetTtsResultOutFileURL(value)
	g._rawJSON = json.RawMessage(data)
	return nil
}

func (g *GetTtsResultOutFileURL) String() string {
	if len(g._rawJSON) > 0 {
		if value, err := core.StringifyJSON(g._rawJSON); err == nil {
			return value
		}
	}
	if value, err := core.StringifyJSON(g); err == nil {
		return value
	}
	return fmt.Sprintf("%#v", g)
}

type OutputFormat string

const (
	OutputFormatWav      OutputFormat = "wav"
	OutputFormatFlac     OutputFormat = "flac"
	OutputFormatAdts     OutputFormat = "adts"
	OutputFormatMp3      OutputFormat = "mp3"
	OutputFormatPcmS16Le OutputFormat = "pcm_s16le"
	OutputFormatPcmS16Be OutputFormat = "pcm_s16be"
	OutputFormatPcmS32Be OutputFormat = "pcm_s32be"
	OutputFormatPcmS32Le OutputFormat = "pcm_s32le"
	OutputFormatPcmF32Le OutputFormat = "pcm_f32le"
	OutputFormatPcmF32Be OutputFormat = "pcm_f32be"
)

func NewOutputFormatFromString(s string) (OutputFormat, error) {
	switch s {
	case "wav":
		return OutputFormatWav, nil
	case "flac":
		return OutputFormatFlac, nil
	case "adts":
		return OutputFormatAdts, nil
	case "mp3":
		return OutputFormatMp3, nil
	case "pcm_s16le":
		return OutputFormatPcmS16Le, nil
	case "pcm_s16be":
		return OutputFormatPcmS16Be, nil
	case "pcm_s32be":
		return OutputFormatPcmS32Be, nil
	case "pcm_s32le":
		return OutputFormatPcmS32Le, nil
	case "pcm_f32le":
		return OutputFormatPcmF32Le, nil
	case "pcm_f32be":
		return OutputFormatPcmF32Be, nil
	}
	var t OutputFormat
	return "", fmt.Errorf("%s is not a valid %T", s, t)
}

func (o OutputFormat) Ptr() *OutputFormat {
	return &o
}

// Advanced options for controlling the TTS inference process.
//
// These options are only supported for the MARS-8 family of speech models.
//
// Attributes:
//
//	stability: A value between 0.0 and 1.0 that controls the stability of
//	    the output audio.
//	temperature: A value between 0.01 and 4.0 that controls the randomness
//	    of the output. Higher values mean more randomness.
//	inference_steps: The number of steps for the diffusion model. A value
//	    between 1 and 1000.
//	speaker_similarity: A value between 0.0 and 1.0 that controls how
//	    similar the output should be to the reference speaker.
type StreamTtsInferenceOptions struct {
	Stability         *float64 `json:"stability,omitempty" url:"stability,omitempty"`
	Temperature       *float64 `json:"temperature,omitempty" url:"temperature,omitempty"`
	InferenceSteps    *int     `json:"inference_steps,omitempty" url:"inference_steps,omitempty"`
	SpeakerSimilarity *float64 `json:"speaker_similarity,omitempty" url:"speaker_similarity,omitempty"`
	LocalizeSpeakerWeight *float64 `json:"localize_speaker_weight,omitempty" url:"localize_speaker_weight,omitempty"`
	AcousticQualityBoost *bool `json:"acoustic_quality_boost,omitempty" url:"acoustic_quality_boost,omitempty"`

	_rawJSON json.RawMessage
}

func (s *StreamTtsInferenceOptions) UnmarshalJSON(data []byte) error {
	type unmarshaler StreamTtsInferenceOptions
	var value unmarshaler
	if err := json.Unmarshal(data, &value); err != nil {
		return err
	}
	*s = StreamTtsInferenceOptions(value)
	s._rawJSON = json.RawMessage(data)
	return nil
}

func (s *StreamTtsInferenceOptions) String() string {
	if len(s._rawJSON) > 0 {
		if value, err := core.StringifyJSON(s._rawJSON); err == nil {
			return value
		}
	}
	if value, err := core.StringifyJSON(s); err == nil {
		return value
	}
	return fmt.Sprintf("%#v", s)
}

// Configuration for the output audio of Streaming TTS.
//
// Attributes:
//
//	format: The format of the output audio. Defaults to MP3.
//	duration: The desired duration of the output audio in seconds. If not
//	    provided, it will be determined automatically.
//	apply_enhancement: Whether to apply audio enhancement to the output.
//	    Defaults to True.
type StreamTtsOutputConfiguration struct {
	Format           *OutputFormat `json:"format,omitempty" url:"format,omitempty"`
	Duration         *float64      `json:"duration,omitempty" url:"duration,omitempty"`
	ApplyEnhancement *bool         `json:"apply_enhancement,omitempty" url:"apply_enhancement,omitempty"`

	_rawJSON json.RawMessage
}

func (s *StreamTtsOutputConfiguration) UnmarshalJSON(data []byte) error {
	type unmarshaler StreamTtsOutputConfiguration
	var value unmarshaler
	if err := json.Unmarshal(data, &value); err != nil {
		return err
	}
	*s = StreamTtsOutputConfiguration(value)
	s._rawJSON = json.RawMessage(data)
	return nil
}

func (s *StreamTtsOutputConfiguration) String() string {
	if len(s._rawJSON) > 0 {
		if value, err := core.StringifyJSON(s._rawJSON); err == nil {
			return value
		}
	}
	if value, err := core.StringifyJSON(s); err == nil {
		return value
	}
	return fmt.Sprintf("%#v", s)
}

// Advanced settings for voice customization.
//
// Attributes:
//
//	enhance_reference_audio_quality: Whether to enhance the quality of the
//	    reference audio before cloning. Defaults to False.
type StreamTtsVoiceSettings struct {
	EnhanceReferenceAudioQuality *bool `json:"enhance_reference_audio_quality,omitempty" url:"enhance_reference_audio_quality,omitempty"`
	MaintainSourceAccent         *bool `json:"maintain_source_accent,omitempty" url:"maintain_source_accent,omitempty"`
	ApplyRefLoudnessNorm         *bool `json:"apply_ref_loudness_norm,omitempty" url:"apply_ref_loudness_norm,omitempty"`

	_rawJSON json.RawMessage
}

func (s *StreamTtsVoiceSettings) UnmarshalJSON(data []byte) error {
	type unmarshaler StreamTtsVoiceSettings
	var value unmarshaler
	if err := json.Unmarshal(data, &value); err != nil {
		return err
	}
	*s = StreamTtsVoiceSettings(value)
	s._rawJSON = json.RawMessage(data)
	return nil
}

func (s *StreamTtsVoiceSettings) String() string {
	if len(s._rawJSON) > 0 {
		if value, err := core.StringifyJSON(s._rawJSON); err == nil {
			return value
		}
	}
	if value, err := core.StringifyJSON(s); err == nil {
		return value
	}
	return fmt.Sprintf("%#v", s)
}

type TtsLanguage string

const (
	TtsLanguageArKw TtsLanguage = "ar-kw"
	TtsLanguageDeCh TtsLanguage = "de-ch"
	TtsLanguageKoKr TtsLanguage = "ko-kr"
	TtsLanguageThTh TtsLanguage = "th-th"
	TtsLanguageMlIn TtsLanguage = "ml-in"
	TtsLanguagePtPt TtsLanguage = "pt-pt"
	TtsLanguageKnIn TtsLanguage = "kn-in"
	TtsLanguageFiFi TtsLanguage = "fi-fi"
	TtsLanguageEsMx TtsLanguage = "es-mx"
	TtsLanguageFrCa TtsLanguage = "fr-ca"
	TtsLanguageCsCz TtsLanguage = "cs-cz"
	TtsLanguagePtBr TtsLanguage = "pt-br"
	TtsLanguageHiIn TtsLanguage = "hi-in"
	TtsLanguageArSy TtsLanguage = "ar-sy"
	TtsLanguageEsUs TtsLanguage = "es-us"
	TtsLanguageBnBd TtsLanguage = "bn-bd"
	TtsLanguageJaJp TtsLanguage = "ja-jp"
	TtsLanguageMrIn TtsLanguage = "mr-in"
	TtsLanguageArMa TtsLanguage = "ar-ma"
	TtsLanguageEsEs TtsLanguage = "es-es"
	TtsLanguageEnUs TtsLanguage = "en-us"
	TtsLanguageZhCn TtsLanguage = "zh-cn"
	TtsLanguageElGr TtsLanguage = "el-gr"
	TtsLanguagePlPl TtsLanguage = "pl-pl"
	TtsLanguageArOm TtsLanguage = "ar-om"
	TtsLanguageFrCh TtsLanguage = "fr-ch"
	TtsLanguageEnUk TtsLanguage = "en-uk"
	TtsLanguageEnAu TtsLanguage = "en-au"
	TtsLanguageArJo TtsLanguage = "ar-jo"
	TtsLanguageArAe TtsLanguage = "ar-ae"
	TtsLanguageTrTr TtsLanguage = "tr-tr"
	TtsLanguageArLy TtsLanguage = "ar-ly"
	TtsLanguageRuRu TtsLanguage = "ru-ru"
	TtsLanguageEnIn TtsLanguage = "en-in"
	TtsLanguageArYe TtsLanguage = "ar-ye"
	TtsLanguageArEg TtsLanguage = "ar-eg"
	TtsLanguageFrBe TtsLanguage = "fr-be"
	TtsLanguageTaIn TtsLanguage = "ta-in"
	TtsLanguageZhTw TtsLanguage = "zh-tw"
	TtsLanguageViVn TtsLanguage = "vi-vn"
	TtsLanguageBnIn TtsLanguage = "bn-in"
	TtsLanguageArSa TtsLanguage = "ar-sa"
	TtsLanguageDeAt TtsLanguage = "de-at"
	TtsLanguagePaIn TtsLanguage = "pa-in"
	TtsLanguageItIt TtsLanguage = "it-it"
	TtsLanguageNlNl TtsLanguage = "nl-nl"
	TtsLanguageArBh TtsLanguage = "ar-bh"
	TtsLanguageFrFr TtsLanguage = "fr-fr"
	TtsLanguageArQa TtsLanguage = "ar-qa"
	TtsLanguageUkUa TtsLanguage = "uk-ua"
	TtsLanguageArTn TtsLanguage = "ar-tn"
	TtsLanguageDeDe TtsLanguage = "de-de"
	TtsLanguageArXa TtsLanguage = "ar-xa"
	TtsLanguageArLb TtsLanguage = "ar-lb"
	TtsLanguageZhHk TtsLanguage = "zh-hk"
	TtsLanguageRoRo TtsLanguage = "ro-ro"
	TtsLanguageAsIn TtsLanguage = "as-in"
	TtsLanguageArIq TtsLanguage = "ar-iq"
	TtsLanguageNlBe TtsLanguage = "nl-be"
	TtsLanguageTeIn TtsLanguage = "te-in"
	TtsLanguageIdId TtsLanguage = "id-id"
	TtsLanguageArDz TtsLanguage = "ar-dz"
)

func NewTtsLanguageFromString(s string) (TtsLanguage, error) {
	switch s {
	case "ar-kw":
		return TtsLanguageArKw, nil
	case "de-ch":
		return TtsLanguageDeCh, nil
	case "ko-kr":
		return TtsLanguageKoKr, nil
	case "th-th":
		return TtsLanguageThTh, nil
	case "ml-in":
		return TtsLanguageMlIn, nil
	case "pt-pt":
		return TtsLanguagePtPt, nil
	case "kn-in":
		return TtsLanguageKnIn, nil
	case "fi-fi":
		return TtsLanguageFiFi, nil
	case "es-mx":
		return TtsLanguageEsMx, nil
	case "fr-ca":
		return TtsLanguageFrCa, nil
	case "cs-cz":
		return TtsLanguageCsCz, nil
	case "pt-br":
		return TtsLanguagePtBr, nil
	case "hi-in":
		return TtsLanguageHiIn, nil
	case "ar-sy":
		return TtsLanguageArSy, nil
	case "es-us":
		return TtsLanguageEsUs, nil
	case "bn-bd":
		return TtsLanguageBnBd, nil
	case "ja-jp":
		return TtsLanguageJaJp, nil
	case "mr-in":
		return TtsLanguageMrIn, nil
	case "ar-ma":
		return TtsLanguageArMa, nil
	case "es-es":
		return TtsLanguageEsEs, nil
	case "en-us":
		return TtsLanguageEnUs, nil
	case "zh-cn":
		return TtsLanguageZhCn, nil
	case "el-gr":
		return TtsLanguageElGr, nil
	case "pl-pl":
		return TtsLanguagePlPl, nil
	case "ar-om":
		return TtsLanguageArOm, nil
	case "fr-ch":
		return TtsLanguageFrCh, nil
	case "en-uk":
		return TtsLanguageEnUk, nil
	case "en-au":
		return TtsLanguageEnAu, nil
	case "ar-jo":
		return TtsLanguageArJo, nil
	case "ar-ae":
		return TtsLanguageArAe, nil
	case "tr-tr":
		return TtsLanguageTrTr, nil
	case "ar-ly":
		return TtsLanguageArLy, nil
	case "ru-ru":
		return TtsLanguageRuRu, nil
	case "en-in":
		return TtsLanguageEnIn, nil
	case "ar-ye":
		return TtsLanguageArYe, nil
	case "ar-eg":
		return TtsLanguageArEg, nil
	case "fr-be":
		return TtsLanguageFrBe, nil
	case "ta-in":
		return TtsLanguageTaIn, nil
	case "zh-tw":
		return TtsLanguageZhTw, nil
	case "vi-vn":
		return TtsLanguageViVn, nil
	case "bn-in":
		return TtsLanguageBnIn, nil
	case "ar-sa":
		return TtsLanguageArSa, nil
	case "de-at":
		return TtsLanguageDeAt, nil
	case "pa-in":
		return TtsLanguagePaIn, nil
	case "it-it":
		return TtsLanguageItIt, nil
	case "nl-nl":
		return TtsLanguageNlNl, nil
	case "ar-bh":
		return TtsLanguageArBh, nil
	case "fr-fr":
		return TtsLanguageFrFr, nil
	case "ar-qa":
		return TtsLanguageArQa, nil
	case "uk-ua":
		return TtsLanguageUkUa, nil
	case "ar-tn":
		return TtsLanguageArTn, nil
	case "de-de":
		return TtsLanguageDeDe, nil
	case "ar-xa":
		return TtsLanguageArXa, nil
	case "ar-lb":
		return TtsLanguageArLb, nil
	case "zh-hk":
		return TtsLanguageZhHk, nil
	case "ro-ro":
		return TtsLanguageRoRo, nil
	case "as-in":
		return TtsLanguageAsIn, nil
	case "ar-iq":
		return TtsLanguageArIq, nil
	case "nl-be":
		return TtsLanguageNlBe, nil
	case "te-in":
		return TtsLanguageTeIn, nil
	case "id-id":
		return TtsLanguageIdId, nil
	case "ar-dz":
		return TtsLanguageArDz, nil
	}
	var t TtsLanguage
	return "", fmt.Errorf("%s is not a valid %T", s, t)
}

func (c TtsLanguage) Ptr() *TtsLanguage {
	return &c
}

type SpeechModel string

const (
	SpeechModelAuto          SpeechModel = "auto"
	SpeechModelMars8         SpeechModel = "mars-8"
	SpeechModelMars8Flash    SpeechModel = "mars-8-flash"
	SpeechModelMars8Instruct SpeechModel = "mars-8-instruct"
	SpeechModelMars7         SpeechModel = "mars-7"
	SpeechModelMars6         SpeechModel = "mars-6"
	SpeechModelMarsPro       SpeechModel = "mars-pro"
	SpeechModelMarsFlash     SpeechModel = "mars-flash"
	SpeechModelMarsInstruct  SpeechModel = "mars-instruct"
)

func NewSpeechModelFromString(s string) (SpeechModel, error) {
	switch s {
	case "auto":
		return SpeechModelAuto, nil
	case "mars-8":
		return SpeechModelMars8, nil
	case "mars-8-flash":
		return SpeechModelMars8Flash, nil
	case "mars-8-instruct":
		return SpeechModelMars8Instruct, nil
	case "mars-7":
		return SpeechModelMars7, nil
	case "mars-6":
		return SpeechModelMars6, nil
	case "mars-pro":
		return SpeechModelMarsPro, nil
	case "mars-flash":
		return SpeechModelMarsFlash, nil
	case "mars-instruct":
		return SpeechModelMarsInstruct, nil
	}
	var t SpeechModel
	return "", fmt.Errorf("%s is not a valid %T", s, t)
}

func (c SpeechModel) Ptr() *SpeechModel {
	return &c
}

type GetTtsResultsTtsResultsPostResponseValue struct {
	typeName               string
	String                 string
	GetTtsResultOutFileURL *GetTtsResultOutFileURL
}

func NewGetTtsResultsTtsResultsPostResponseValueFromString(value string) *GetTtsResultsTtsResultsPostResponseValue {
	return &GetTtsResultsTtsResultsPostResponseValue{typeName: "string", String: value}
}

func NewGetTtsResultsTtsResultsPostResponseValueFromGetTtsResultOutFileURL(value *GetTtsResultOutFileURL) *GetTtsResultsTtsResultsPostResponseValue {
	return &GetTtsResultsTtsResultsPostResponseValue{typeName: "getTtsResultOutFileURL", GetTtsResultOutFileURL: value}
}

func (g *GetTtsResultsTtsResultsPostResponseValue) UnmarshalJSON(data []byte) error {
	var valueString string
	if err := json.Unmarshal(data, &valueString); err == nil {
		g.typeName = "string"
		g.String = valueString
		return nil
	}
	valueGetTtsResultOutFileURL := new(GetTtsResultOutFileURL)
	if err := json.Unmarshal(data, &valueGetTtsResultOutFileURL); err == nil {
		g.typeName = "getTtsResultOutFileURL"
		g.GetTtsResultOutFileURL = valueGetTtsResultOutFileURL
		return nil
	}
	return fmt.Errorf("%s cannot be deserialized as a %T", data, g)
}

func (g GetTtsResultsTtsResultsPostResponseValue) MarshalJSON() ([]byte, error) {
	switch g.typeName {
	default:
		return nil, fmt.Errorf("invalid type %s in %T", g.typeName, g)
	case "string":
		return json.Marshal(g.String)
	case "getTtsResultOutFileURL":
		return json.Marshal(g.GetTtsResultOutFileURL)
	}
}

type GetTtsResultsTtsResultsPostResponseValueVisitor interface {
	VisitString(string) error
	VisitGetTtsResultOutFileURL(*GetTtsResultOutFileURL) error
}

func (g *GetTtsResultsTtsResultsPostResponseValue) Accept(visitor GetTtsResultsTtsResultsPostResponseValueVisitor) error {
	switch g.typeName {
	default:
		return fmt.Errorf("invalid type %s in %T", g.typeName, g)
	case "string":
		return visitor.VisitString(g.String)
	case "getTtsResultOutFileURL":
		return visitor.VisitGetTtsResultOutFileURL(g.GetTtsResultOutFileURL)
	}
}

type GetTtsRunInfoTtsResultRunIDGetResponse struct {
	typeName               string
	String                 string
	GetTtsResultOutFileURL *GetTtsResultOutFileURL
}

func NewGetTtsRunInfoTtsResultRunIDGetResponseFromString(value string) *GetTtsRunInfoTtsResultRunIDGetResponse {
	return &GetTtsRunInfoTtsResultRunIDGetResponse{typeName: "string", String: value}
}

func NewGetTtsRunInfoTtsResultRunIDGetResponseFromGetTtsResultOutFileURL(value *GetTtsResultOutFileURL) *GetTtsRunInfoTtsResultRunIDGetResponse {
	return &GetTtsRunInfoTtsResultRunIDGetResponse{typeName: "getTtsResultOutFileURL", GetTtsResultOutFileURL: value}
}

func (g *GetTtsRunInfoTtsResultRunIDGetResponse) UnmarshalJSON(data []byte) error {
	var valueString string
	if err := json.Unmarshal(data, &valueString); err == nil {
		g.typeName = "string"
		g.String = valueString
		return nil
	}
	valueGetTtsResultOutFileURL := new(GetTtsResultOutFileURL)
	if err := json.Unmarshal(data, &valueGetTtsResultOutFileURL); err == nil {
		g.typeName = "getTtsResultOutFileURL"
		g.GetTtsResultOutFileURL = valueGetTtsResultOutFileURL
		return nil
	}
	return fmt.Errorf("%s cannot be deserialized as a %T", data, g)
}

func (g GetTtsRunInfoTtsResultRunIDGetResponse) MarshalJSON() ([]byte, error) {
	switch g.typeName {
	default:
		return nil, fmt.Errorf("invalid type %s in %T", g.typeName, g)
	case "string":
		return json.Marshal(g.String)
	case "getTtsResultOutFileURL":
		return json.Marshal(g.GetTtsResultOutFileURL)
	}
}

type GetTtsRunInfoTtsResultRunIDGetResponseVisitor interface {
	VisitString(string) error
	VisitGetTtsResultOutFileURL(*GetTtsResultOutFileURL) error
}

func (g *GetTtsRunInfoTtsResultRunIDGetResponse) Accept(visitor GetTtsRunInfoTtsResultRunIDGetResponseVisitor) error {
	switch g.typeName {
	default:
		return fmt.Errorf("invalid type %s in %T", g.typeName, g)
	case "string":
		return visitor.VisitString(g.String)
	case "getTtsResultOutFileURL":
		return visitor.VisitGetTtsResultOutFileURL(g.GetTtsResultOutFileURL)
	}
}
