// This file was auto-generated by Fern from our API Definition.

package api

import (
	json "encoding/json"
	fmt "fmt"
	core "sdk/core"
)

type CreateTextToAudioRequestPayload struct {
	Traceparent        *string `json:"-" url:"-"`
	RunID              *int    `json:"-" url:"run_id,omitempty"`
	ProjectName        *string `json:"project_name,omitempty" url:"-"`
	ProjectDescription *string `json:"project_description,omitempty" url:"-"`
	FolderID           *int    `json:"folder_id,omitempty" url:"-"`
	// The text to be converted to audio.
	Prompt string `json:"prompt" url:"-"`
	// The desired duration of the audio.
	Duration *float64 `json:"duration,omitempty" url:"-"`
	// The audio type preference.
	AudioType *TextToAudioType `json:"audio_type,omitempty" url:"-"`
}

type GetTextToAudioResultTextToSoundResultRunIDGetRequest struct {
	// Output format for the Text To Speech result
	OutputType *string `json:"-" url:"output_type,omitempty"`
}

type GetTextToAudioStatusTextToSoundTaskIDGetRequest struct {
	RunID *int `json:"-" url:"run_id,omitempty"`
}

type GetTextToSoundResultsTextToSoundResultsPostRequest struct {
	Traceparent *string               `json:"-" url:"-"`
	RunID       *int                  `json:"-" url:"run_id,omitempty"`
	Body        *RunIDsRequestPayload `json:"-" url:"-"`
}

func (g *GetTextToSoundResultsTextToSoundResultsPostRequest) UnmarshalJSON(data []byte) error {
	body := new(RunIDsRequestPayload)
	if err := json.Unmarshal(data, &body); err != nil {
		return err
	}
	g.Body = body
	return nil
}

func (g *GetTextToSoundResultsTextToSoundResultsPostRequest) MarshalJSON() ([]byte, error) {
	return json.Marshal(g.Body)
}

type TextToAudioResult struct {
	OutputURL string `json:"output_url" url:"output_url"`

	extraProperties map[string]interface{}
	_rawJSON        json.RawMessage
}

func (t *TextToAudioResult) GetOutputURL() string {
	if t == nil {
		return ""
	}
	return t.OutputURL
}

func (t *TextToAudioResult) GetExtraProperties() map[string]interface{} {
	return t.extraProperties
}

func (t *TextToAudioResult) UnmarshalJSON(data []byte) error {
	type unmarshaler TextToAudioResult
	var value unmarshaler
	if err := json.Unmarshal(data, &value); err != nil {
		return err
	}
	*t = TextToAudioResult(value)

	extraProperties, err := core.ExtractExtraProperties(data, *t)
	if err != nil {
		return err
	}
	t.extraProperties = extraProperties

	t._rawJSON = json.RawMessage(data)
	return nil
}

func (t *TextToAudioResult) String() string {
	if len(t._rawJSON) > 0 {
		if value, err := core.StringifyJSON(t._rawJSON); err == nil {
			return value
		}
	}
	if value, err := core.StringifyJSON(t); err == nil {
		return value
	}
	return fmt.Sprintf("%#v", t)
}

type TextToAudioType string

const (
	TextToAudioTypeSound TextToAudioType = "sound"
	TextToAudioTypeMusic TextToAudioType = "music"
)

func NewTextToAudioTypeFromString(s string) (TextToAudioType, error) {
	switch s {
	case "sound":
		return TextToAudioTypeSound, nil
	case "music":
		return TextToAudioTypeMusic, nil
	}
	var t TextToAudioType
	return "", fmt.Errorf("%s is not a valid %T", s, t)
}

func (t TextToAudioType) Ptr() *TextToAudioType {
	return &t
}
