// This file was auto-generated by Fern from our API Definition.

package api

import (
	json "encoding/json"
	fmt "fmt"
	core "sdk/core"
)

type CreateTextToVoiceRequestPayload struct {
	Traceparent        *string `json:"-" url:"-"`
	ProjectName        *string `json:"project_name,omitempty" url:"-"`
	ProjectDescription *string `json:"project_description,omitempty" url:"-"`
	FolderID           *int    `json:"folder_id,omitempty" url:"-"`
	// The text to be converted to voice
	Text string `json:"text" url:"-"`
	// Description to use for the created voice
	VoiceDescription string `json:"voice_description" url:"-"`
}

type GetTextToVoiceResultTextToVoiceResultRunIDGetRequest struct {
}

type GetTextToVoiceStatusTextToVoiceTaskIDGetRequest struct {
	Traceparent *string `json:"-" url:"-"`
	RunID       *int    `json:"-" url:"run_id,omitempty"`
}

type GetTextToVoiceResultOut struct {
	Previews []string `json:"previews,omitempty" url:"previews,omitempty"`

	extraProperties map[string]interface{}
	_rawJSON        json.RawMessage
}

func (g *GetTextToVoiceResultOut) GetPreviews() []string {
	if g == nil {
		return nil
	}
	return g.Previews
}

func (g *GetTextToVoiceResultOut) GetExtraProperties() map[string]interface{} {
	return g.extraProperties
}

func (g *GetTextToVoiceResultOut) UnmarshalJSON(data []byte) error {
	type unmarshaler GetTextToVoiceResultOut
	var value unmarshaler
	if err := json.Unmarshal(data, &value); err != nil {
		return err
	}
	*g = GetTextToVoiceResultOut(value)

	extraProperties, err := core.ExtractExtraProperties(data, *g)
	if err != nil {
		return err
	}
	g.extraProperties = extraProperties

	g._rawJSON = json.RawMessage(data)
	return nil
}

func (g *GetTextToVoiceResultOut) String() string {
	if len(g._rawJSON) > 0 {
		if value, err := core.StringifyJSON(g._rawJSON); err == nil {
			return value
		}
	}
	if value, err := core.StringifyJSON(g); err == nil {
		return value
	}
	return fmt.Sprintf("%#v", g)
}
