// This file was auto-generated by Fern from our API Definition.

package api

import (
	json "encoding/json"
	fmt "fmt"
	core "sdk/core"
)

type CreateTranslatedTtsRequestPayload struct {
	Traceparent        *string      `json:"-" url:"-"`
	RunID              *int         `json:"-" url:"run_id,omitempty"`
	ProjectName        *string      `json:"project_name,omitempty" url:"-"`
	ProjectDescription *string      `json:"project_description,omitempty" url:"-"`
	FolderID           *int         `json:"folder_id,omitempty" url:"-"`
	Text               string       `json:"text" url:"-"`
	VoiceID            int          `json:"voice_id" url:"-"`
	Age                *int         `json:"age,omitempty" url:"-"`
	Formality          *Formalities `json:"formality,omitempty" url:"-"`
	Gender             *Gender      `json:"gender,omitempty" url:"-"`
	SourceLanguage     Languages    `json:"source_language" url:"-"`
	TargetLanguage     Languages    `json:"target_language" url:"-"`
	ChosenDictionaries []int        `json:"chosen_dictionaries,omitempty" url:"-"`
}

type GetTranslatedTtsTaskStatusTranslatedTtsTaskIDGetRequest struct {
	RunID *int `json:"-" url:"run_id,omitempty"`
}

type CreateTranslatedTtsOut struct {
	TaskID string `json:"task_id" url:"task_id"`

	extraProperties map[string]interface{}
	_rawJSON        json.RawMessage
}

func (c *CreateTranslatedTtsOut) GetTaskID() string {
	if c == nil {
		return ""
	}
	return c.TaskID
}

func (c *CreateTranslatedTtsOut) GetExtraProperties() map[string]interface{} {
	return c.extraProperties
}

func (c *CreateTranslatedTtsOut) UnmarshalJSON(data []byte) error {
	type unmarshaler CreateTranslatedTtsOut
	var value unmarshaler
	if err := json.Unmarshal(data, &value); err != nil {
		return err
	}
	*c = CreateTranslatedTtsOut(value)

	extraProperties, err := core.ExtractExtraProperties(data, *c)
	if err != nil {
		return err
	}
	c.extraProperties = extraProperties

	c._rawJSON = json.RawMessage(data)
	return nil
}

func (c *CreateTranslatedTtsOut) String() string {
	if len(c._rawJSON) > 0 {
		if value, err := core.StringifyJSON(c._rawJSON); err == nil {
			return value
		}
	}
	if value, err := core.StringifyJSON(c); err == nil {
		return value
	}
	return fmt.Sprintf("%#v", c)
}
