// This file was auto-generated by Fern from our API Definition.

package api

import (
	json "encoding/json"
	fmt "fmt"
	core "sdk/core"
)

type CreateTranslationRequestPayload struct {
	RunID              *int         `json:"-" url:"run_id,omitempty"`
	ProjectName        *string      `json:"project_name,omitempty" url:"-"`
	ProjectDescription *string      `json:"project_description,omitempty" url:"-"`
	FolderID           *int         `json:"folder_id,omitempty" url:"-"`
	Texts              []string     `json:"texts,omitempty" url:"-"`
	Age                *int         `json:"age,omitempty" url:"-"`
	Formality          *Formalities `json:"formality,omitempty" url:"-"`
	Gender             *Gender      `json:"gender,omitempty" url:"-"`
	SourceLanguage     Languages    `json:"source_language" url:"-"`
	TargetLanguage     Languages    `json:"target_language" url:"-"`
	ChosenDictionaries []int        `json:"chosen_dictionaries,omitempty" url:"-"`
}

type GetTranslationResultTranslationResultRunIDGetRequest struct {
	Traceparent *string `json:"-" url:"-"`
}

type GetTranslationResultsTranslationResultsPostRequest struct {
	Traceparent *string               `json:"-" url:"-"`
	RunID       *int                  `json:"-" url:"run_id,omitempty"`
	Body        *RunIDsRequestPayload `json:"-" url:"-"`
}

func (g *GetTranslationResultsTranslationResultsPostRequest) UnmarshalJSON(data []byte) error {
	body := new(RunIDsRequestPayload)
	if err := json.Unmarshal(data, &body); err != nil {
		return err
	}
	g.Body = body
	return nil
}

func (g *GetTranslationResultsTranslationResultsPostRequest) MarshalJSON() ([]byte, error) {
	return json.Marshal(g.Body)
}

type GetTranslationTaskStatusTranslateTaskIDGetRequest struct {
	RunID *int `json:"-" url:"run_id,omitempty"`
}

type CreateTranslationStreamRequestPayload struct {
	Traceparent        *string      `json:"-" url:"-"`
	SourceLanguage     Languages    `json:"source_language" url:"-"`
	TargetLanguage     Languages    `json:"target_language" url:"-"`
	Text               string       `json:"text" url:"-"`
	Formality          *Formalities `json:"formality,omitempty" url:"-"`
	Gender             *Gender      `json:"gender,omitempty" url:"-"`
	TeamID             *int         `json:"team_id,omitempty" url:"-"`
	ProjectName        *string      `json:"project_name,omitempty" url:"-"`
	ProjectDescription *string      `json:"project_description,omitempty" url:"-"`
	FolderID           *int         `json:"folder_id,omitempty" url:"-"`
}

type TranslationResult struct {
	Texts []string `json:"texts,omitempty" url:"texts,omitempty"`

	extraProperties map[string]interface{}
	_rawJSON        json.RawMessage
}

func (t *TranslationResult) GetTexts() []string {
	if t == nil {
		return nil
	}
	return t.Texts
}

func (t *TranslationResult) GetExtraProperties() map[string]interface{} {
	return t.extraProperties
}

func (t *TranslationResult) UnmarshalJSON(data []byte) error {
	type unmarshaler TranslationResult
	var value unmarshaler
	if err := json.Unmarshal(data, &value); err != nil {
		return err
	}
	*t = TranslationResult(value)

	extraProperties, err := core.ExtractExtraProperties(data, *t)
	if err != nil {
		return err
	}
	t.extraProperties = extraProperties

	t._rawJSON = json.RawMessage(data)
	return nil
}

func (t *TranslationResult) String() string {
	if len(t._rawJSON) > 0 {
		if value, err := core.StringifyJSON(t._rawJSON); err == nil {
			return value
		}
	}
	if value, err := core.StringifyJSON(t); err == nil {
		return value
	}
	return fmt.Sprintf("%#v", t)
}
