// This file was auto-generated by Fern from our API Definition.

package api

import (
	json "encoding/json"
	fmt "fmt"
	core "sdk/core"
	time "time"
)

type AudioStream struct {
	Index          int                    `json:"index" url:"index"`
	CodecName      string                 `json:"codec_name" url:"codec_name"`
	CodecLongName  string                 `json:"codec_long_name" url:"codec_long_name"`
	CodecTagString *string                `json:"codec_tag_string,omitempty" url:"codec_tag_string,omitempty"`
	CodecTag       *string                `json:"codec_tag,omitempty" url:"codec_tag,omitempty"`
	Profile        *string                `json:"profile,omitempty" url:"profile,omitempty"`
	SampleFmt      string                 `json:"sample_fmt" url:"sample_fmt"`
	SampleRate     int                    `json:"sample_rate" url:"sample_rate"`
	Channels       int                    `json:"channels" url:"channels"`
	ChannelLayout  *string                `json:"channel_layout,omitempty" url:"channel_layout,omitempty"`
	ID             *string                `json:"id,omitempty" url:"id,omitempty"`
	BitRate        *int                   `json:"bit_rate,omitempty" url:"bit_rate,omitempty"`
	Tags           map[string]interface{} `json:"tags,omitempty" url:"tags,omitempty"`

	extraProperties map[string]interface{}
	_rawJSON        json.RawMessage
}

func (a *AudioStream) GetIndex() int {
	if a == nil {
		return 0
	}
	return a.Index
}

func (a *AudioStream) GetCodecName() string {
	if a == nil {
		return ""
	}
	return a.CodecName
}

func (a *AudioStream) GetCodecLongName() string {
	if a == nil {
		return ""
	}
	return a.CodecLongName
}

func (a *AudioStream) GetCodecTagString() *string {
	if a == nil {
		return nil
	}
	return a.CodecTagString
}

func (a *AudioStream) GetCodecTag() *string {
	if a == nil {
		return nil
	}
	return a.CodecTag
}

func (a *AudioStream) GetProfile() *string {
	if a == nil {
		return nil
	}
	return a.Profile
}

func (a *AudioStream) GetSampleFmt() string {
	if a == nil {
		return ""
	}
	return a.SampleFmt
}

func (a *AudioStream) GetSampleRate() int {
	if a == nil {
		return 0
	}
	return a.SampleRate
}

func (a *AudioStream) GetChannels() int {
	if a == nil {
		return 0
	}
	return a.Channels
}

func (a *AudioStream) GetChannelLayout() *string {
	if a == nil {
		return nil
	}
	return a.ChannelLayout
}

func (a *AudioStream) GetID() *string {
	if a == nil {
		return nil
	}
	return a.ID
}

func (a *AudioStream) GetBitRate() *int {
	if a == nil {
		return nil
	}
	return a.BitRate
}

func (a *AudioStream) GetTags() map[string]interface{} {
	if a == nil {
		return nil
	}
	return a.Tags
}

func (a *AudioStream) GetExtraProperties() map[string]interface{} {
	return a.extraProperties
}

func (a *AudioStream) UnmarshalJSON(data []byte) error {
	type unmarshaler AudioStream
	var value unmarshaler
	if err := json.Unmarshal(data, &value); err != nil {
		return err
	}
	*a = AudioStream(value)

	extraProperties, err := core.ExtractExtraProperties(data, *a)
	if err != nil {
		return err
	}
	a.extraProperties = extraProperties

	a._rawJSON = json.RawMessage(data)
	return nil
}

func (a *AudioStream) String() string {
	if len(a._rawJSON) > 0 {
		if value, err := core.StringifyJSON(a._rawJSON); err == nil {
			return value
		}
	}
	if value, err := core.StringifyJSON(a); err == nil {
		return value
	}
	return fmt.Sprintf("%#v", a)
}

type ConfigStream struct {
	Pipeline *ConfigStreamPipeline `json:"pipeline,omitempty" url:"pipeline,omitempty"`
	Mixing   *OverdubConfig        `json:"mixing,omitempty" url:"mixing,omitempty"`

	extraProperties map[string]interface{}
	_rawJSON        json.RawMessage
}

func (c *ConfigStream) GetPipeline() *ConfigStreamPipeline {
	if c == nil {
		return nil
	}
	return c.Pipeline
}

func (c *ConfigStream) GetMixing() *OverdubConfig {
	if c == nil {
		return nil
	}
	return c.Mixing
}

func (c *ConfigStream) GetExtraProperties() map[string]interface{} {
	return c.extraProperties
}

func (c *ConfigStream) UnmarshalJSON(data []byte) error {
	type unmarshaler ConfigStream
	var value unmarshaler
	if err := json.Unmarshal(data, &value); err != nil {
		return err
	}
	*c = ConfigStream(value)

	extraProperties, err := core.ExtractExtraProperties(data, *c)
	if err != nil {
		return err
	}
	c.extraProperties = extraProperties

	c._rawJSON = json.RawMessage(data)
	return nil
}

func (c *ConfigStream) String() string {
	if len(c._rawJSON) > 0 {
		if value, err := core.StringifyJSON(c._rawJSON); err == nil {
			return value
		}
	}
	if value, err := core.StringifyJSON(c); err == nil {
		return value
	}
	return fmt.Sprintf("%#v", c)
}

type ConfigStreamPipeline struct {
	Demixing     *DemixingOption     `json:"demixing,omitempty" url:"demixing,omitempty"`
	Segmenting   *SegmentingOption   `json:"segmenting,omitempty" url:"segmenting,omitempty"`
	Transcribing *TranscribingOption `json:"transcribing,omitempty" url:"transcribing,omitempty"`
	Translating  *TranslatingOption  `json:"translating,omitempty" url:"translating,omitempty"`
	Revoicing    *RevoicingOption    `json:"revoicing,omitempty" url:"revoicing,omitempty"`

	extraProperties map[string]interface{}
	_rawJSON        json.RawMessage
}

func (c *ConfigStreamPipeline) GetDemixing() *DemixingOption {
	if c == nil {
		return nil
	}
	return c.Demixing
}

func (c *ConfigStreamPipeline) GetSegmenting() *SegmentingOption {
	if c == nil {
		return nil
	}
	return c.Segmenting
}

func (c *ConfigStreamPipeline) GetTranscribing() *TranscribingOption {
	if c == nil {
		return nil
	}
	return c.Transcribing
}

func (c *ConfigStreamPipeline) GetTranslating() *TranslatingOption {
	if c == nil {
		return nil
	}
	return c.Translating
}

func (c *ConfigStreamPipeline) GetRevoicing() *RevoicingOption {
	if c == nil {
		return nil
	}
	return c.Revoicing
}

func (c *ConfigStreamPipeline) GetExtraProperties() map[string]interface{} {
	return c.extraProperties
}

func (c *ConfigStreamPipeline) UnmarshalJSON(data []byte) error {
	type unmarshaler ConfigStreamPipeline
	var value unmarshaler
	if err := json.Unmarshal(data, &value); err != nil {
		return err
	}
	*c = ConfigStreamPipeline(value)

	extraProperties, err := core.ExtractExtraProperties(data, *c)
	if err != nil {
		return err
	}
	c.extraProperties = extraProperties

	c._rawJSON = json.RawMessage(data)
	return nil
}

func (c *ConfigStreamPipeline) String() string {
	if len(c._rawJSON) > 0 {
		if value, err := core.StringifyJSON(c._rawJSON); err == nil {
			return value
		}
	}
	if value, err := core.StringifyJSON(c); err == nil {
		return value
	}
	return fmt.Sprintf("%#v", c)
}

type CreateStreamOut struct {
	StreamID              int                      `json:"stream_id" url:"stream_id"`
	StreamURLForLanguages []*StreamURLForLanguages `json:"stream_url_for_languages,omitempty" url:"stream_url_for_languages,omitempty"`
	TaskID                string                   `json:"task_id" url:"task_id"`

	extraProperties map[string]interface{}
	_rawJSON        json.RawMessage
}

func (c *CreateStreamOut) GetStreamID() int {
	if c == nil {
		return 0
	}
	return c.StreamID
}

func (c *CreateStreamOut) GetStreamURLForLanguages() []*StreamURLForLanguages {
	if c == nil {
		return nil
	}
	return c.StreamURLForLanguages
}

func (c *CreateStreamOut) GetTaskID() string {
	if c == nil {
		return ""
	}
	return c.TaskID
}

func (c *CreateStreamOut) GetExtraProperties() map[string]interface{} {
	return c.extraProperties
}

func (c *CreateStreamOut) UnmarshalJSON(data []byte) error {
	type unmarshaler CreateStreamOut
	var value unmarshaler
	if err := json.Unmarshal(data, &value); err != nil {
		return err
	}
	*c = CreateStreamOut(value)

	extraProperties, err := core.ExtractExtraProperties(data, *c)
	if err != nil {
		return err
	}
	c.extraProperties = extraProperties

	c._rawJSON = json.RawMessage(data)
	return nil
}

func (c *CreateStreamOut) String() string {
	if len(c._rawJSON) > 0 {
		if value, err := core.StringifyJSON(c._rawJSON); err == nil {
			return value
		}
	}
	if value, err := core.StringifyJSON(c); err == nil {
		return value
	}
	return fmt.Sprintf("%#v", c)
}

type CreateStreamRequestPayload struct {
	// The name of the stream.
	Name *string `json:"name,omitempty" url:"name,omitempty"`
	// The description of the stream.
	Description *string `json:"description,omitempty" url:"description,omitempty"`
	// The initial delay in seconds before starting the stream creation process.
	InitialDelay *int `json:"initial_delay,omitempty" url:"initial_delay,omitempty"`
	// The maximum duration in minutes for the stream creation process before timing out.
	TimeoutInMins *int `json:"timeout_in_mins,omitempty" url:"timeout_in_mins,omitempty"`
	// List of voice identifiers to be used in the stream.
	Voices []int `json:"voices,omitempty" url:"voices,omitempty"`
	// List of dictionary identifiers to be used in the stream.
	Dictionaries []int `json:"dictionaries,omitempty" url:"dictionaries,omitempty"`
	// The shared configuration for the streaming pipeline.
	Config *ConfigStream `json:"config,omitempty" url:"config,omitempty"`
	// The source stream configuration details.
	SourceStream *SourceStream `json:"source_stream,omitempty" url:"source_stream,omitempty"`
	// List of target stream configurations.
	TargetStreams []*TargetStream `json:"target_streams,omitempty" url:"target_streams,omitempty"`
	StartTime     *time.Time      `json:"start_time,omitempty" url:"start_time,omitempty"`
	EndTime       *time.Time      `json:"end_time,omitempty" url:"end_time,omitempty"`
	Timezone      *string         `json:"timezone,omitempty" url:"timezone,omitempty"`

	extraProperties map[string]interface{}
	_rawJSON        json.RawMessage
}

func (c *CreateStreamRequestPayload) GetName() *string {
	if c == nil {
		return nil
	}
	return c.Name
}

func (c *CreateStreamRequestPayload) GetDescription() *string {
	if c == nil {
		return nil
	}
	return c.Description
}

func (c *CreateStreamRequestPayload) GetInitialDelay() *int {
	if c == nil {
		return nil
	}
	return c.InitialDelay
}

func (c *CreateStreamRequestPayload) GetTimeoutInMins() *int {
	if c == nil {
		return nil
	}
	return c.TimeoutInMins
}

func (c *CreateStreamRequestPayload) GetVoices() []int {
	if c == nil {
		return nil
	}
	return c.Voices
}

func (c *CreateStreamRequestPayload) GetDictionaries() []int {
	if c == nil {
		return nil
	}
	return c.Dictionaries
}

func (c *CreateStreamRequestPayload) GetConfig() *ConfigStream {
	if c == nil {
		return nil
	}
	return c.Config
}

func (c *CreateStreamRequestPayload) GetSourceStream() *SourceStream {
	if c == nil {
		return nil
	}
	return c.SourceStream
}

func (c *CreateStreamRequestPayload) GetTargetStreams() []*TargetStream {
	if c == nil {
		return nil
	}
	return c.TargetStreams
}

func (c *CreateStreamRequestPayload) GetStartTime() *time.Time {
	if c == nil {
		return nil
	}
	return c.StartTime
}

func (c *CreateStreamRequestPayload) GetEndTime() *time.Time {
	if c == nil {
		return nil
	}
	return c.EndTime
}

func (c *CreateStreamRequestPayload) GetTimezone() *string {
	if c == nil {
		return nil
	}
	return c.Timezone
}

func (c *CreateStreamRequestPayload) GetExtraProperties() map[string]interface{} {
	return c.extraProperties
}

func (c *CreateStreamRequestPayload) UnmarshalJSON(data []byte) error {
	type embed CreateStreamRequestPayload
	var unmarshaler = struct {
		embed
		StartTime *core.DateTime `json:"start_time,omitempty"`
		EndTime   *core.DateTime `json:"end_time,omitempty"`
	}{
		embed: embed(*c),
	}
	if err := json.Unmarshal(data, &unmarshaler); err != nil {
		return err
	}
	*c = CreateStreamRequestPayload(unmarshaler.embed)
	c.StartTime = unmarshaler.StartTime.TimePtr()
	c.EndTime = unmarshaler.EndTime.TimePtr()

	extraProperties, err := core.ExtractExtraProperties(data, *c)
	if err != nil {
		return err
	}
	c.extraProperties = extraProperties

	c._rawJSON = json.RawMessage(data)
	return nil
}

func (c *CreateStreamRequestPayload) MarshalJSON() ([]byte, error) {
	type embed CreateStreamRequestPayload
	var marshaler = struct {
		embed
		StartTime *core.DateTime `json:"start_time,omitempty"`
		EndTime   *core.DateTime `json:"end_time,omitempty"`
	}{
		embed:     embed(*c),
		StartTime: core.NewOptionalDateTime(c.StartTime),
		EndTime:   core.NewOptionalDateTime(c.EndTime),
	}
	return json.Marshal(marshaler)
}

func (c *CreateStreamRequestPayload) String() string {
	if len(c._rawJSON) > 0 {
		if value, err := core.StringifyJSON(c._rawJSON); err == nil {
			return value
		}
	}
	if value, err := core.StringifyJSON(c); err == nil {
		return value
	}
	return fmt.Sprintf("%#v", c)
}

type DataStream struct {
	Index          int     `json:"index" url:"index"`
	CodecName      *string `json:"codec_name,omitempty" url:"codec_name,omitempty"`
	CodecLongName  *string `json:"codec_long_name,omitempty" url:"codec_long_name,omitempty"`
	CodecTagString *string `json:"codec_tag_string,omitempty" url:"codec_tag_string,omitempty"`
	CodecTag       *string `json:"codec_tag,omitempty" url:"codec_tag,omitempty"`
	ID             *string `json:"id,omitempty" url:"id,omitempty"`

	extraProperties map[string]interface{}
	_rawJSON        json.RawMessage
}

func (d *DataStream) GetIndex() int {
	if d == nil {
		return 0
	}
	return d.Index
}

func (d *DataStream) GetCodecName() *string {
	if d == nil {
		return nil
	}
	return d.CodecName
}

func (d *DataStream) GetCodecLongName() *string {
	if d == nil {
		return nil
	}
	return d.CodecLongName
}

func (d *DataStream) GetCodecTagString() *string {
	if d == nil {
		return nil
	}
	return d.CodecTagString
}

func (d *DataStream) GetCodecTag() *string {
	if d == nil {
		return nil
	}
	return d.CodecTag
}

func (d *DataStream) GetID() *string {
	if d == nil {
		return nil
	}
	return d.ID
}

func (d *DataStream) GetExtraProperties() map[string]interface{} {
	return d.extraProperties
}

func (d *DataStream) UnmarshalJSON(data []byte) error {
	type unmarshaler DataStream
	var value unmarshaler
	if err := json.Unmarshal(data, &value); err != nil {
		return err
	}
	*d = DataStream(value)

	extraProperties, err := core.ExtractExtraProperties(data, *d)
	if err != nil {
		return err
	}
	d.extraProperties = extraProperties

	d._rawJSON = json.RawMessage(data)
	return nil
}

func (d *DataStream) String() string {
	if len(d._rawJSON) > 0 {
		if value, err := core.StringifyJSON(d._rawJSON); err == nil {
			return value
		}
	}
	if value, err := core.StringifyJSON(d); err == nil {
		return value
	}
	return fmt.Sprintf("%#v", d)
}

type DemixingOption string

const (
	DemixingOptionNone              DemixingOption = "none"
	DemixingOptionPickLeftChannel   DemixingOption = "pick_left_channel"
	DemixingOptionPickRightChannel  DemixingOption = "pick_right_channel"
	DemixingOptionPickCenterChannel DemixingOption = "pick_center_channel"
	DemixingOptionBestModel         DemixingOption = "best_model"
	DemixingOptionFastModel         DemixingOption = "fast_model"
)

func NewDemixingOptionFromString(s string) (DemixingOption, error) {
	switch s {
	case "none":
		return DemixingOptionNone, nil
	case "pick_left_channel":
		return DemixingOptionPickLeftChannel, nil
	case "pick_right_channel":
		return DemixingOptionPickRightChannel, nil
	case "pick_center_channel":
		return DemixingOptionPickCenterChannel, nil
	case "best_model":
		return DemixingOptionBestModel, nil
	case "fast_model":
		return DemixingOptionFastModel, nil
	}
	var t DemixingOption
	return "", fmt.Errorf("%s is not a valid %T", s, t)
}

func (d DemixingOption) Ptr() *DemixingOption {
	return &d
}

type ExceptionReasons string

const (
	ExceptionReasonsHarmfulContentDetected       ExceptionReasons = "HARMFUL_CONTENT_DETECTED"
	ExceptionReasonsVoiceConversionError         ExceptionReasons = "VOICE_CONVERSION_ERROR"
	ExceptionReasonsProcessingError              ExceptionReasons = "PROCESSING_ERROR"
	ExceptionReasonsSourceTooLong                ExceptionReasons = "SOURCE_TOO_LONG"
	ExceptionReasonsSourceTooLarge               ExceptionReasons = "SOURCE_TOO_LARGE"
	ExceptionReasonsSourceTypeNotSupported       ExceptionReasons = "SOURCE_TYPE_NOT_SUPPORTED"
	ExceptionReasonsErrorDownloadingSource       ExceptionReasons = "ERROR_DOWNLOADING_SOURCE"
	ExceptionReasonsTooManyGdriveRequests        ExceptionReasons = "TOO_MANY_GDRIVE_REQUESTS"
	ExceptionReasonsSourceBlockedInRegion        ExceptionReasons = "SOURCE_BLOCKED_IN_REGION"
	ExceptionReasonsSourceIsAgeRestricted        ExceptionReasons = "SOURCE_IS_AGE_RESTRICTED"
	ExceptionReasonsSourceNotFound               ExceptionReasons = "SOURCE_NOT_FOUND"
	ExceptionReasonsMismatchedSourceCodec        ExceptionReasons = "MISMATCHED_SOURCE_CODEC"
	ExceptionReasonsContentDoesNotMatchExtension ExceptionReasons = "CONTENT_DOES_NOT_MATCH_EXTENSION"
	ExceptionReasonsInvalidSourceData            ExceptionReasons = "INVALID_SOURCE_DATA"
	ExceptionReasonsVideoDoesNotHaveAudioStreams ExceptionReasons = "VIDEO_DOES_NOT_HAVE_AUDIO_STREAMS"
	ExceptionReasonsMasteringOutOfRange          ExceptionReasons = "MASTERING_OUT_OF_RANGE"
	ExceptionReasonsInvalidAudioTracksSelection  ExceptionReasons = "INVALID_AUDIO_TRACKS_SELECTION"
	ExceptionReasonsPaymentRequired              ExceptionReasons = "PAYMENT_REQUIRED"
	ExceptionReasonsForbidden                    ExceptionReasons = "FORBIDDEN"
	ExceptionReasonsInternalError                ExceptionReasons = "INTERNAL_ERROR"
	ExceptionReasonsNone                         ExceptionReasons = "NONE"
)

func NewExceptionReasonsFromString(s string) (ExceptionReasons, error) {
	switch s {
	case "HARMFUL_CONTENT_DETECTED":
		return ExceptionReasonsHarmfulContentDetected, nil
	case "VOICE_CONVERSION_ERROR":
		return ExceptionReasonsVoiceConversionError, nil
	case "PROCESSING_ERROR":
		return ExceptionReasonsProcessingError, nil
	case "SOURCE_TOO_LONG":
		return ExceptionReasonsSourceTooLong, nil
	case "SOURCE_TOO_LARGE":
		return ExceptionReasonsSourceTooLarge, nil
	case "SOURCE_TYPE_NOT_SUPPORTED":
		return ExceptionReasonsSourceTypeNotSupported, nil
	case "ERROR_DOWNLOADING_SOURCE":
		return ExceptionReasonsErrorDownloadingSource, nil
	case "TOO_MANY_GDRIVE_REQUESTS":
		return ExceptionReasonsTooManyGdriveRequests, nil
	case "SOURCE_BLOCKED_IN_REGION":
		return ExceptionReasonsSourceBlockedInRegion, nil
	case "SOURCE_IS_AGE_RESTRICTED":
		return ExceptionReasonsSourceIsAgeRestricted, nil
	case "SOURCE_NOT_FOUND":
		return ExceptionReasonsSourceNotFound, nil
	case "MISMATCHED_SOURCE_CODEC":
		return ExceptionReasonsMismatchedSourceCodec, nil
	case "CONTENT_DOES_NOT_MATCH_EXTENSION":
		return ExceptionReasonsContentDoesNotMatchExtension, nil
	case "INVALID_SOURCE_DATA":
		return ExceptionReasonsInvalidSourceData, nil
	case "VIDEO_DOES_NOT_HAVE_AUDIO_STREAMS":
		return ExceptionReasonsVideoDoesNotHaveAudioStreams, nil
	case "MASTERING_OUT_OF_RANGE":
		return ExceptionReasonsMasteringOutOfRange, nil
	case "INVALID_AUDIO_TRACKS_SELECTION":
		return ExceptionReasonsInvalidAudioTracksSelection, nil
	case "PAYMENT_REQUIRED":
		return ExceptionReasonsPaymentRequired, nil
	case "FORBIDDEN":
		return ExceptionReasonsForbidden, nil
	case "INTERNAL_ERROR":
		return ExceptionReasonsInternalError, nil
	case "NONE":
		return ExceptionReasonsNone, nil
	}
	var t ExceptionReasons
	return "", fmt.Errorf("%s is not a valid %T", s, t)
}

func (e ExceptionReasons) Ptr() *ExceptionReasons {
	return &e
}

type Formalities = int

type Gender = int

type GetProbeStreamIn struct {
	URL        string  `json:"url" url:"url"`
	Passphrase *string `json:"passphrase,omitempty" url:"passphrase,omitempty"`
	StreamID   *string `json:"stream_id,omitempty" url:"stream_id,omitempty"`

	extraProperties map[string]interface{}
	_rawJSON        json.RawMessage
}

func (g *GetProbeStreamIn) GetURL() string {
	if g == nil {
		return ""
	}
	return g.URL
}

func (g *GetProbeStreamIn) GetPassphrase() *string {
	if g == nil {
		return nil
	}
	return g.Passphrase
}

func (g *GetProbeStreamIn) GetStreamID() *string {
	if g == nil {
		return nil
	}
	return g.StreamID
}

func (g *GetProbeStreamIn) GetExtraProperties() map[string]interface{} {
	return g.extraProperties
}

func (g *GetProbeStreamIn) UnmarshalJSON(data []byte) error {
	type unmarshaler GetProbeStreamIn
	var value unmarshaler
	if err := json.Unmarshal(data, &value); err != nil {
		return err
	}
	*g = GetProbeStreamIn(value)

	extraProperties, err := core.ExtractExtraProperties(data, *g)
	if err != nil {
		return err
	}
	g.extraProperties = extraProperties

	g._rawJSON = json.RawMessage(data)
	return nil
}

func (g *GetProbeStreamIn) String() string {
	if len(g._rawJSON) > 0 {
		if value, err := core.StringifyJSON(g._rawJSON); err == nil {
			return value
		}
	}
	if value, err := core.StringifyJSON(g); err == nil {
		return value
	}
	return fmt.Sprintf("%#v", g)
}

type GetProbeStreamOut struct {
	VideoStreams []*VideoStream `json:"video_streams,omitempty" url:"video_streams,omitempty"`
	AudioStreams []*AudioStream `json:"audio_streams,omitempty" url:"audio_streams,omitempty"`
	DataStreams  []*DataStream  `json:"data_streams,omitempty" url:"data_streams,omitempty"`

	extraProperties map[string]interface{}
	_rawJSON        json.RawMessage
}

func (g *GetProbeStreamOut) GetVideoStreams() []*VideoStream {
	if g == nil {
		return nil
	}
	return g.VideoStreams
}

func (g *GetProbeStreamOut) GetAudioStreams() []*AudioStream {
	if g == nil {
		return nil
	}
	return g.AudioStreams
}

func (g *GetProbeStreamOut) GetDataStreams() []*DataStream {
	if g == nil {
		return nil
	}
	return g.DataStreams
}

func (g *GetProbeStreamOut) GetExtraProperties() map[string]interface{} {
	return g.extraProperties
}

func (g *GetProbeStreamOut) UnmarshalJSON(data []byte) error {
	type unmarshaler GetProbeStreamOut
	var value unmarshaler
	if err := json.Unmarshal(data, &value); err != nil {
		return err
	}
	*g = GetProbeStreamOut(value)

	extraProperties, err := core.ExtractExtraProperties(data, *g)
	if err != nil {
		return err
	}
	g.extraProperties = extraProperties

	g._rawJSON = json.RawMessage(data)
	return nil
}

func (g *GetProbeStreamOut) String() string {
	if len(g._rawJSON) > 0 {
		if value, err := core.StringifyJSON(g._rawJSON); err == nil {
			return value
		}
	}
	if value, err := core.StringifyJSON(g); err == nil {
		return value
	}
	return fmt.Sprintf("%#v", g)
}

type HTTPValidationError struct {
	Detail []*ValidationError `json:"detail,omitempty" url:"detail,omitempty"`

	extraProperties map[string]interface{}
	_rawJSON        json.RawMessage
}

func (h *HTTPValidationError) GetDetail() []*ValidationError {
	if h == nil {
		return nil
	}
	return h.Detail
}

func (h *HTTPValidationError) GetExtraProperties() map[string]interface{} {
	return h.extraProperties
}

func (h *HTTPValidationError) UnmarshalJSON(data []byte) error {
	type unmarshaler HTTPValidationError
	var value unmarshaler
	if err := json.Unmarshal(data, &value); err != nil {
		return err
	}
	*h = HTTPValidationError(value)

	extraProperties, err := core.ExtractExtraProperties(data, *h)
	if err != nil {
		return err
	}
	h.extraProperties = extraProperties

	h._rawJSON = json.RawMessage(data)
	return nil
}

func (h *HTTPValidationError) String() string {
	if len(h._rawJSON) > 0 {
		if value, err := core.StringifyJSON(h._rawJSON); err == nil {
			return value
		}
	}
	if value, err := core.StringifyJSON(h); err == nil {
		return value
	}
	return fmt.Sprintf("%#v", h)
}

type Languages = int

type OrchestratorPipelineCallResult struct {
	TaskID *string `json:"task_id,omitempty" url:"task_id,omitempty"`

	extraProperties map[string]interface{}
	_rawJSON        json.RawMessage
}

func (o *OrchestratorPipelineCallResult) GetTaskID() *string {
	if o == nil {
		return nil
	}
	return o.TaskID
}

func (o *OrchestratorPipelineCallResult) GetExtraProperties() map[string]interface{} {
	return o.extraProperties
}

func (o *OrchestratorPipelineCallResult) UnmarshalJSON(data []byte) error {
	type unmarshaler OrchestratorPipelineCallResult
	var value unmarshaler
	if err := json.Unmarshal(data, &value); err != nil {
		return err
	}
	*o = OrchestratorPipelineCallResult(value)

	extraProperties, err := core.ExtractExtraProperties(data, *o)
	if err != nil {
		return err
	}
	o.extraProperties = extraProperties

	o._rawJSON = json.RawMessage(data)
	return nil
}

func (o *OrchestratorPipelineCallResult) String() string {
	if len(o._rawJSON) > 0 {
		if value, err := core.StringifyJSON(o._rawJSON); err == nil {
			return value
		}
	}
	if value, err := core.StringifyJSON(o); err == nil {
		return value
	}
	return fmt.Sprintf("%#v", o)
}

type OrchestratorPipelineResult struct {
	Status          TaskStatus                                 `json:"status" url:"status"`
	RunID           *int                                       `json:"run_id,omitempty" url:"run_id,omitempty"`
	ExceptionReason *OrchestratorPipelineResultExceptionReason `json:"exception_reason,omitempty" url:"exception_reason,omitempty"`
	Message         *OrchestratorPipelineResultMessage         `json:"message,omitempty" url:"message,omitempty"`

	extraProperties map[string]interface{}
	_rawJSON        json.RawMessage
}

func (o *OrchestratorPipelineResult) GetStatus() TaskStatus {
	if o == nil {
		return ""
	}
	return o.Status
}

func (o *OrchestratorPipelineResult) GetRunID() *int {
	if o == nil {
		return nil
	}
	return o.RunID
}

func (o *OrchestratorPipelineResult) GetExceptionReason() *OrchestratorPipelineResultExceptionReason {
	if o == nil {
		return nil
	}
	return o.ExceptionReason
}

func (o *OrchestratorPipelineResult) GetMessage() *OrchestratorPipelineResultMessage {
	if o == nil {
		return nil
	}
	return o.Message
}

func (o *OrchestratorPipelineResult) GetExtraProperties() map[string]interface{} {
	return o.extraProperties
}

func (o *OrchestratorPipelineResult) UnmarshalJSON(data []byte) error {
	type unmarshaler OrchestratorPipelineResult
	var value unmarshaler
	if err := json.Unmarshal(data, &value); err != nil {
		return err
	}
	*o = OrchestratorPipelineResult(value)

	extraProperties, err := core.ExtractExtraProperties(data, *o)
	if err != nil {
		return err
	}
	o.extraProperties = extraProperties

	o._rawJSON = json.RawMessage(data)
	return nil
}

func (o *OrchestratorPipelineResult) String() string {
	if len(o._rawJSON) > 0 {
		if value, err := core.StringifyJSON(o._rawJSON); err == nil {
			return value
		}
	}
	if value, err := core.StringifyJSON(o); err == nil {
		return value
	}
	return fmt.Sprintf("%#v", o)
}

type OrchestratorPipelineResultExceptionReason struct {
	String           string
	ExceptionReasons ExceptionReasons

	typ string
}

func NewOrchestratorPipelineResultExceptionReasonFromString(value string) *OrchestratorPipelineResultExceptionReason {
	return &OrchestratorPipelineResultExceptionReason{typ: "String", String: value}
}

func NewOrchestratorPipelineResultExceptionReasonFromExceptionReasons(value ExceptionReasons) *OrchestratorPipelineResultExceptionReason {
	return &OrchestratorPipelineResultExceptionReason{typ: "ExceptionReasons", ExceptionReasons: value}
}

func (o *OrchestratorPipelineResultExceptionReason) GetString() string {
	if o == nil {
		return ""
	}
	return o.String
}

func (o *OrchestratorPipelineResultExceptionReason) GetExceptionReasons() ExceptionReasons {
	if o == nil {
		return ""
	}
	return o.ExceptionReasons
}

func (o *OrchestratorPipelineResultExceptionReason) UnmarshalJSON(data []byte) error {
	var valueString string
	if err := json.Unmarshal(data, &valueString); err == nil {
		o.typ = "String"
		o.String = valueString
		return nil
	}
	var valueExceptionReasons ExceptionReasons
	if err := json.Unmarshal(data, &valueExceptionReasons); err == nil {
		o.typ = "ExceptionReasons"
		o.ExceptionReasons = valueExceptionReasons
		return nil
	}
	return fmt.Errorf("%s cannot be deserialized as a %T", data, o)
}

func (o OrchestratorPipelineResultExceptionReason) MarshalJSON() ([]byte, error) {
	if o.typ == "String" || o.String != "" {
		return json.Marshal(o.String)
	}
	if o.typ == "ExceptionReasons" || o.ExceptionReasons != "" {
		return json.Marshal(o.ExceptionReasons)
	}
	return nil, fmt.Errorf("type %T does not include a non-empty union type", o)
}

type OrchestratorPipelineResultExceptionReasonVisitor interface {
	VisitString(string) error
	VisitExceptionReasons(ExceptionReasons) error
}

func (o *OrchestratorPipelineResultExceptionReason) Accept(visitor OrchestratorPipelineResultExceptionReasonVisitor) error {
	if o.typ == "String" || o.String != "" {
		return visitor.VisitString(o.String)
	}
	if o.typ == "ExceptionReasons" || o.ExceptionReasons != "" {
		return visitor.VisitExceptionReasons(o.ExceptionReasons)
	}
	return fmt.Errorf("type %T does not include a non-empty union type", o)
}

type OrchestratorPipelineResultMessage struct {
	StringUnknownMap map[string]interface{}
	String           string

	typ string
}

func NewOrchestratorPipelineResultMessageFromStringUnknownMap(value map[string]interface{}) *OrchestratorPipelineResultMessage {
	return &OrchestratorPipelineResultMessage{typ: "StringUnknownMap", StringUnknownMap: value}
}

func NewOrchestratorPipelineResultMessageFromString(value string) *OrchestratorPipelineResultMessage {
	return &OrchestratorPipelineResultMessage{typ: "String", String: value}
}

func (o *OrchestratorPipelineResultMessage) GetStringUnknownMap() map[string]interface{} {
	if o == nil {
		return nil
	}
	return o.StringUnknownMap
}

func (o *OrchestratorPipelineResultMessage) GetString() string {
	if o == nil {
		return ""
	}
	return o.String
}

func (o *OrchestratorPipelineResultMessage) UnmarshalJSON(data []byte) error {
	var valueStringUnknownMap map[string]interface{}
	if err := json.Unmarshal(data, &valueStringUnknownMap); err == nil {
		o.typ = "StringUnknownMap"
		o.StringUnknownMap = valueStringUnknownMap
		return nil
	}
	var valueString string
	if err := json.Unmarshal(data, &valueString); err == nil {
		o.typ = "String"
		o.String = valueString
		return nil
	}
	return fmt.Errorf("%s cannot be deserialized as a %T", data, o)
}

func (o OrchestratorPipelineResultMessage) MarshalJSON() ([]byte, error) {
	if o.typ == "StringUnknownMap" || o.StringUnknownMap != nil {
		return json.Marshal(o.StringUnknownMap)
	}
	if o.typ == "String" || o.String != "" {
		return json.Marshal(o.String)
	}
	return nil, fmt.Errorf("type %T does not include a non-empty union type", o)
}

type OrchestratorPipelineResultMessageVisitor interface {
	VisitStringUnknownMap(map[string]interface{}) error
	VisitString(string) error
}

func (o *OrchestratorPipelineResultMessage) Accept(visitor OrchestratorPipelineResultMessageVisitor) error {
	if o.typ == "StringUnknownMap" || o.StringUnknownMap != nil {
		return visitor.VisitStringUnknownMap(o.StringUnknownMap)
	}
	if o.typ == "String" || o.String != "" {
		return visitor.VisitString(o.String)
	}
	return fmt.Errorf("type %T does not include a non-empty union type", o)
}

type OverdubConfig struct {
	// Proportion of the original audio (0.0 to 1.0).
	OriginalAudioGain *float64 `json:"original_audio_gain,omitempty" url:"original_audio_gain,omitempty"`
	// Proportion of the background audio (0.0 to 1.0).
	BackgroundAudioGain *float64 `json:"background_audio_gain,omitempty" url:"background_audio_gain,omitempty"`
	// Cross-fade duration in seconds (0.0 to 5.0).
	FadeTime *float64 `json:"fade_time,omitempty" url:"fade_time,omitempty"`
	// Proportion of the fallback audio (0.0 to 1.0) (for streaming only).
	FallbackAudioGain *float64 `json:"fallback_audio_gain,omitempty" url:"fallback_audio_gain,omitempty"`

	extraProperties map[string]interface{}
	_rawJSON        json.RawMessage
}

func (o *OverdubConfig) GetOriginalAudioGain() *float64 {
	if o == nil {
		return nil
	}
	return o.OriginalAudioGain
}

func (o *OverdubConfig) GetBackgroundAudioGain() *float64 {
	if o == nil {
		return nil
	}
	return o.BackgroundAudioGain
}

func (o *OverdubConfig) GetFadeTime() *float64 {
	if o == nil {
		return nil
	}
	return o.FadeTime
}

func (o *OverdubConfig) GetFallbackAudioGain() *float64 {
	if o == nil {
		return nil
	}
	return o.FallbackAudioGain
}

func (o *OverdubConfig) GetExtraProperties() map[string]interface{} {
	return o.extraProperties
}

func (o *OverdubConfig) UnmarshalJSON(data []byte) error {
	type unmarshaler OverdubConfig
	var value unmarshaler
	if err := json.Unmarshal(data, &value); err != nil {
		return err
	}
	*o = OverdubConfig(value)

	extraProperties, err := core.ExtractExtraProperties(data, *o)
	if err != nil {
		return err
	}
	o.extraProperties = extraProperties

	o._rawJSON = json.RawMessage(data)
	return nil
}

func (o *OverdubConfig) String() string {
	if len(o._rawJSON) > 0 {
		if value, err := core.StringifyJSON(o._rawJSON); err == nil {
			return value
		}
	}
	if value, err := core.StringifyJSON(o); err == nil {
		return value
	}
	return fmt.Sprintf("%#v", o)
}

type RevoicingOption string

const (
	RevoicingOptionNone      RevoicingOption = "none"
	RevoicingOptionBestModel RevoicingOption = "best_model"
	RevoicingOptionFastModel RevoicingOption = "fast_model"
)

func NewRevoicingOptionFromString(s string) (RevoicingOption, error) {
	switch s {
	case "none":
		return RevoicingOptionNone, nil
	case "best_model":
		return RevoicingOptionBestModel, nil
	case "fast_model":
		return RevoicingOptionFastModel, nil
	}
	var t RevoicingOption
	return "", fmt.Errorf("%s is not a valid %T", s, t)
}

func (r RevoicingOption) Ptr() *RevoicingOption {
	return &r
}

type RunIDsRequestPayload struct {
	RunIDs []int `json:"run_ids,omitempty" url:"run_ids,omitempty"`

	extraProperties map[string]interface{}
	_rawJSON        json.RawMessage
}

func (r *RunIDsRequestPayload) GetRunIDs() []int {
	if r == nil {
		return nil
	}
	return r.RunIDs
}

func (r *RunIDsRequestPayload) GetExtraProperties() map[string]interface{} {
	return r.extraProperties
}

func (r *RunIDsRequestPayload) UnmarshalJSON(data []byte) error {
	type unmarshaler RunIDsRequestPayload
	var value unmarshaler
	if err := json.Unmarshal(data, &value); err != nil {
		return err
	}
	*r = RunIDsRequestPayload(value)

	extraProperties, err := core.ExtractExtraProperties(data, *r)
	if err != nil {
		return err
	}
	r.extraProperties = extraProperties

	r._rawJSON = json.RawMessage(data)
	return nil
}

func (r *RunIDsRequestPayload) String() string {
	if len(r._rawJSON) > 0 {
		if value, err := core.StringifyJSON(r._rawJSON); err == nil {
			return value
		}
	}
	if value, err := core.StringifyJSON(r); err == nil {
		return value
	}
	return fmt.Sprintf("%#v", r)
}

type SegmentingOption string

const (
	SegmentingOptionNone      SegmentingOption = "none"
	SegmentingOptionLoudness  SegmentingOption = "loudness"
	SegmentingOptionBestModel SegmentingOption = "best_model"
	SegmentingOptionFastModel SegmentingOption = "fast_model"
)

func NewSegmentingOptionFromString(s string) (SegmentingOption, error) {
	switch s {
	case "none":
		return SegmentingOptionNone, nil
	case "loudness":
		return SegmentingOptionLoudness, nil
	case "best_model":
		return SegmentingOptionBestModel, nil
	case "fast_model":
		return SegmentingOptionFastModel, nil
	}
	var t SegmentingOption
	return "", fmt.Errorf("%s is not a valid %T", s, t)
}

func (s SegmentingOption) Ptr() *SegmentingOption {
	return &s
}

type SourceStream struct {
	Language              Languages       `json:"language" url:"language"`
	URL                   string          `json:"url" url:"url"`
	Category              *StreamCategory `json:"category,omitempty" url:"category,omitempty"`
	Passphrase            *string         `json:"passphrase,omitempty" url:"passphrase,omitempty"`
	Streamid              *string         `json:"streamid,omitempty" url:"streamid,omitempty"`
	NumberOfStreams       *int            `json:"number_of_streams,omitempty" url:"number_of_streams,omitempty"`
	AudioStream           *int            `json:"audio_stream,omitempty" url:"audio_stream,omitempty"`
	BackgroundAudioStream *int            `json:"background_audio_stream,omitempty" url:"background_audio_stream,omitempty"`
	Latency               *int            `json:"latency,omitempty" url:"latency,omitempty"`
	RelayInput            *bool           `json:"relay_input,omitempty" url:"relay_input,omitempty"`

	extraProperties map[string]interface{}
	_rawJSON        json.RawMessage
}

func (s *SourceStream) GetLanguage() Languages {
	if s == nil {
		return 0
	}
	return s.Language
}

func (s *SourceStream) GetURL() string {
	if s == nil {
		return ""
	}
	return s.URL
}

func (s *SourceStream) GetCategory() *StreamCategory {
	if s == nil {
		return nil
	}
	return s.Category
}

func (s *SourceStream) GetPassphrase() *string {
	if s == nil {
		return nil
	}
	return s.Passphrase
}

func (s *SourceStream) GetStreamid() *string {
	if s == nil {
		return nil
	}
	return s.Streamid
}

func (s *SourceStream) GetNumberOfStreams() *int {
	if s == nil {
		return nil
	}
	return s.NumberOfStreams
}

func (s *SourceStream) GetAudioStream() *int {
	if s == nil {
		return nil
	}
	return s.AudioStream
}

func (s *SourceStream) GetBackgroundAudioStream() *int {
	if s == nil {
		return nil
	}
	return s.BackgroundAudioStream
}

func (s *SourceStream) GetLatency() *int {
	if s == nil {
		return nil
	}
	return s.Latency
}

func (s *SourceStream) GetRelayInput() *bool {
	if s == nil {
		return nil
	}
	return s.RelayInput
}

func (s *SourceStream) GetExtraProperties() map[string]interface{} {
	return s.extraProperties
}

func (s *SourceStream) UnmarshalJSON(data []byte) error {
	type unmarshaler SourceStream
	var value unmarshaler
	if err := json.Unmarshal(data, &value); err != nil {
		return err
	}
	*s = SourceStream(value)

	extraProperties, err := core.ExtractExtraProperties(data, *s)
	if err != nil {
		return err
	}
	s.extraProperties = extraProperties

	s._rawJSON = json.RawMessage(data)
	return nil
}

func (s *SourceStream) String() string {
	if len(s._rawJSON) > 0 {
		if value, err := core.StringifyJSON(s._rawJSON); err == nil {
			return value
		}
	}
	if value, err := core.StringifyJSON(s); err == nil {
		return value
	}
	return fmt.Sprintf("%#v", s)
}

type StreamCategory = int

type StreamType = int

type StreamURLForLanguages struct {
	Languages []Languages `json:"languages,omitempty" url:"languages,omitempty"`
	URL       string      `json:"url" url:"url"`

	extraProperties map[string]interface{}
	_rawJSON        json.RawMessage
}

func (s *StreamURLForLanguages) GetLanguages() []Languages {
	if s == nil {
		return nil
	}
	return s.Languages
}

func (s *StreamURLForLanguages) GetURL() string {
	if s == nil {
		return ""
	}
	return s.URL
}

func (s *StreamURLForLanguages) GetExtraProperties() map[string]interface{} {
	return s.extraProperties
}

func (s *StreamURLForLanguages) UnmarshalJSON(data []byte) error {
	type unmarshaler StreamURLForLanguages
	var value unmarshaler
	if err := json.Unmarshal(data, &value); err != nil {
		return err
	}
	*s = StreamURLForLanguages(value)

	extraProperties, err := core.ExtractExtraProperties(data, *s)
	if err != nil {
		return err
	}
	s.extraProperties = extraProperties

	s._rawJSON = json.RawMessage(data)
	return nil
}

func (s *StreamURLForLanguages) String() string {
	if len(s._rawJSON) > 0 {
		if value, err := core.StringifyJSON(s._rawJSON); err == nil {
			return value
		}
	}
	if value, err := core.StringifyJSON(s); err == nil {
		return value
	}
	return fmt.Sprintf("%#v", s)
}

type TargetStream struct {
	Languages          []Languages `json:"languages,omitempty" url:"languages,omitempty"`
	URL                string      `json:"url" url:"url"`
	Type               StreamType  `json:"type" url:"type"`
	Passphrase         *string     `json:"passphrase,omitempty" url:"passphrase,omitempty"`
	Streamid           *string     `json:"streamid,omitempty" url:"streamid,omitempty"`
	Pids               []*int      `json:"pids,omitempty" url:"pids,omitempty"`
	TranscodeVideo     *bool       `json:"transcode_video,omitempty" url:"transcode_video,omitempty"`
	EmbedSubtitles     *bool       `json:"embed_subtitles,omitempty" url:"embed_subtitles,omitempty"`
	AudioCodec         *string     `json:"audio_codec,omitempty" url:"audio_codec,omitempty"`
	AudioBitrate       *string     `json:"audio_bitrate,omitempty" url:"audio_bitrate,omitempty"`
	AudioChannelLayout *string     `json:"audio_channel_layout,omitempty" url:"audio_channel_layout,omitempty"`
	Latency            *int        `json:"latency,omitempty" url:"latency,omitempty"`
	ConstantBitrate    *bool       `json:"constant_bitrate,omitempty" url:"constant_bitrate,omitempty"`
	RelayOutput        *bool       `json:"relay_output,omitempty" url:"relay_output,omitempty"`

	extraProperties map[string]interface{}
	_rawJSON        json.RawMessage
}

func (t *TargetStream) GetLanguages() []Languages {
	if t == nil {
		return nil
	}
	return t.Languages
}

func (t *TargetStream) GetURL() string {
	if t == nil {
		return ""
	}
	return t.URL
}

func (t *TargetStream) GetType() StreamType {
	if t == nil {
		return 0
	}
	return t.Type
}

func (t *TargetStream) GetPassphrase() *string {
	if t == nil {
		return nil
	}
	return t.Passphrase
}

func (t *TargetStream) GetStreamid() *string {
	if t == nil {
		return nil
	}
	return t.Streamid
}

func (t *TargetStream) GetPids() []*int {
	if t == nil {
		return nil
	}
	return t.Pids
}

func (t *TargetStream) GetTranscodeVideo() *bool {
	if t == nil {
		return nil
	}
	return t.TranscodeVideo
}

func (t *TargetStream) GetEmbedSubtitles() *bool {
	if t == nil {
		return nil
	}
	return t.EmbedSubtitles
}

func (t *TargetStream) GetAudioCodec() *string {
	if t == nil {
		return nil
	}
	return t.AudioCodec
}

func (t *TargetStream) GetAudioBitrate() *string {
	if t == nil {
		return nil
	}
	return t.AudioBitrate
}

func (t *TargetStream) GetAudioChannelLayout() *string {
	if t == nil {
		return nil
	}
	return t.AudioChannelLayout
}

func (t *TargetStream) GetLatency() *int {
	if t == nil {
		return nil
	}
	return t.Latency
}

func (t *TargetStream) GetConstantBitrate() *bool {
	if t == nil {
		return nil
	}
	return t.ConstantBitrate
}

func (t *TargetStream) GetRelayOutput() *bool {
	if t == nil {
		return nil
	}
	return t.RelayOutput
}

func (t *TargetStream) GetExtraProperties() map[string]interface{} {
	return t.extraProperties
}

func (t *TargetStream) UnmarshalJSON(data []byte) error {
	type unmarshaler TargetStream
	var value unmarshaler
	if err := json.Unmarshal(data, &value); err != nil {
		return err
	}
	*t = TargetStream(value)

	extraProperties, err := core.ExtractExtraProperties(data, *t)
	if err != nil {
		return err
	}
	t.extraProperties = extraProperties

	t._rawJSON = json.RawMessage(data)
	return nil
}

func (t *TargetStream) String() string {
	if len(t._rawJSON) > 0 {
		if value, err := core.StringifyJSON(t._rawJSON); err == nil {
			return value
		}
	}
	if value, err := core.StringifyJSON(t); err == nil {
		return value
	}
	return fmt.Sprintf("%#v", t)
}

type TaskStatus string

const (
	TaskStatusSuccess TaskStatus = "SUCCESS"
	TaskStatusPending TaskStatus = "PENDING"
	TaskStatusError   TaskStatus = "ERROR"
)

func NewTaskStatusFromString(s string) (TaskStatus, error) {
	switch s {
	case "SUCCESS":
		return TaskStatusSuccess, nil
	case "PENDING":
		return TaskStatusPending, nil
	case "ERROR":
		return TaskStatusError, nil
	}
	var t TaskStatus
	return "", fmt.Errorf("%s is not a valid %T", s, t)
}

func (t TaskStatus) Ptr() *TaskStatus {
	return &t
}

type TranscribingOption string

const (
	TranscribingOptionNone      TranscribingOption = "none"
	TranscribingOptionBestModel TranscribingOption = "best_model"
	TranscribingOptionFastModel TranscribingOption = "fast_model"
)

func NewTranscribingOptionFromString(s string) (TranscribingOption, error) {
	switch s {
	case "none":
		return TranscribingOptionNone, nil
	case "best_model":
		return TranscribingOptionBestModel, nil
	case "fast_model":
		return TranscribingOptionFastModel, nil
	}
	var t TranscribingOption
	return "", fmt.Errorf("%s is not a valid %T", s, t)
}

func (t TranscribingOption) Ptr() *TranscribingOption {
	return &t
}

type Transcript struct {
	Start   float64 `json:"start" url:"start"`
	End     float64 `json:"end" url:"end"`
	Text    string  `json:"text" url:"text"`
	Speaker string  `json:"speaker" url:"speaker"`

	extraProperties map[string]interface{}
	_rawJSON        json.RawMessage
}

func (t *Transcript) GetStart() float64 {
	if t == nil {
		return 0
	}
	return t.Start
}

func (t *Transcript) GetEnd() float64 {
	if t == nil {
		return 0
	}
	return t.End
}

func (t *Transcript) GetText() string {
	if t == nil {
		return ""
	}
	return t.Text
}

func (t *Transcript) GetSpeaker() string {
	if t == nil {
		return ""
	}
	return t.Speaker
}

func (t *Transcript) GetExtraProperties() map[string]interface{} {
	return t.extraProperties
}

func (t *Transcript) UnmarshalJSON(data []byte) error {
	type unmarshaler Transcript
	var value unmarshaler
	if err := json.Unmarshal(data, &value); err != nil {
		return err
	}
	*t = Transcript(value)

	extraProperties, err := core.ExtractExtraProperties(data, *t)
	if err != nil {
		return err
	}
	t.extraProperties = extraProperties

	t._rawJSON = json.RawMessage(data)
	return nil
}

func (t *Transcript) String() string {
	if len(t._rawJSON) > 0 {
		if value, err := core.StringifyJSON(t._rawJSON); err == nil {
			return value
		}
	}
	if value, err := core.StringifyJSON(t); err == nil {
		return value
	}
	return fmt.Sprintf("%#v", t)
}

type TranslatingOption string

const (
	TranslatingOptionNone      TranslatingOption = "none"
	TranslatingOptionBestModel TranslatingOption = "best_model"
	TranslatingOptionFastModel TranslatingOption = "fast_model"
)

func NewTranslatingOptionFromString(s string) (TranslatingOption, error) {
	switch s {
	case "none":
		return TranslatingOptionNone, nil
	case "best_model":
		return TranslatingOptionBestModel, nil
	case "fast_model":
		return TranslatingOptionFastModel, nil
	}
	var t TranslatingOption
	return "", fmt.Errorf("%s is not a valid %T", s, t)
}

func (t TranslatingOption) Ptr() *TranslatingOption {
	return &t
}

type ValidationError struct {
	Loc  []*ValidationErrorLocItem `json:"loc,omitempty" url:"loc,omitempty"`
	Msg  string                    `json:"msg" url:"msg"`
	Type string                    `json:"type" url:"type"`

	extraProperties map[string]interface{}
	_rawJSON        json.RawMessage
}

func (v *ValidationError) GetLoc() []*ValidationErrorLocItem {
	if v == nil {
		return nil
	}
	return v.Loc
}

func (v *ValidationError) GetMsg() string {
	if v == nil {
		return ""
	}
	return v.Msg
}

func (v *ValidationError) GetType() string {
	if v == nil {
		return ""
	}
	return v.Type
}

func (v *ValidationError) GetExtraProperties() map[string]interface{} {
	return v.extraProperties
}

func (v *ValidationError) UnmarshalJSON(data []byte) error {
	type unmarshaler ValidationError
	var value unmarshaler
	if err := json.Unmarshal(data, &value); err != nil {
		return err
	}
	*v = ValidationError(value)

	extraProperties, err := core.ExtractExtraProperties(data, *v)
	if err != nil {
		return err
	}
	v.extraProperties = extraProperties

	v._rawJSON = json.RawMessage(data)
	return nil
}

func (v *ValidationError) String() string {
	if len(v._rawJSON) > 0 {
		if value, err := core.StringifyJSON(v._rawJSON); err == nil {
			return value
		}
	}
	if value, err := core.StringifyJSON(v); err == nil {
		return value
	}
	return fmt.Sprintf("%#v", v)
}

type ValidationErrorLocItem struct {
	String  string
	Integer int

	typ string
}

func NewValidationErrorLocItemFromString(value string) *ValidationErrorLocItem {
	return &ValidationErrorLocItem{typ: "String", String: value}
}

func NewValidationErrorLocItemFromInteger(value int) *ValidationErrorLocItem {
	return &ValidationErrorLocItem{typ: "Integer", Integer: value}
}

func (v *ValidationErrorLocItem) GetString() string {
	if v == nil {
		return ""
	}
	return v.String
}

func (v *ValidationErrorLocItem) GetInteger() int {
	if v == nil {
		return 0
	}
	return v.Integer
}

func (v *ValidationErrorLocItem) UnmarshalJSON(data []byte) error {
	var valueString string
	if err := json.Unmarshal(data, &valueString); err == nil {
		v.typ = "String"
		v.String = valueString
		return nil
	}
	var valueInteger int
	if err := json.Unmarshal(data, &valueInteger); err == nil {
		v.typ = "Integer"
		v.Integer = valueInteger
		return nil
	}
	return fmt.Errorf("%s cannot be deserialized as a %T", data, v)
}

func (v ValidationErrorLocItem) MarshalJSON() ([]byte, error) {
	if v.typ == "String" || v.String != "" {
		return json.Marshal(v.String)
	}
	if v.typ == "Integer" || v.Integer != 0 {
		return json.Marshal(v.Integer)
	}
	return nil, fmt.Errorf("type %T does not include a non-empty union type", v)
}

type ValidationErrorLocItemVisitor interface {
	VisitString(string) error
	VisitInteger(int) error
}

func (v *ValidationErrorLocItem) Accept(visitor ValidationErrorLocItemVisitor) error {
	if v.typ == "String" || v.String != "" {
		return visitor.VisitString(v.String)
	}
	if v.typ == "Integer" || v.Integer != 0 {
		return visitor.VisitInteger(v.Integer)
	}
	return fmt.Errorf("type %T does not include a non-empty union type", v)
}

type VideoStream struct {
	Index          int     `json:"index" url:"index"`
	CodecName      string  `json:"codec_name" url:"codec_name"`
	CodecLongName  string  `json:"codec_long_name" url:"codec_long_name"`
	CodecTagString *string `json:"codec_tag_string,omitempty" url:"codec_tag_string,omitempty"`
	CodecTag       *string `json:"codec_tag,omitempty" url:"codec_tag,omitempty"`
	Profile        *string `json:"profile,omitempty" url:"profile,omitempty"`
	Width          *int    `json:"width,omitempty" url:"width,omitempty"`
	Height         *int    `json:"height,omitempty" url:"height,omitempty"`
	IsAvc          *bool   `json:"is_avc,omitempty" url:"is_avc,omitempty"`
	ID             *string `json:"id,omitempty" url:"id,omitempty"`

	extraProperties map[string]interface{}
	_rawJSON        json.RawMessage
}

func (v *VideoStream) GetIndex() int {
	if v == nil {
		return 0
	}
	return v.Index
}

func (v *VideoStream) GetCodecName() string {
	if v == nil {
		return ""
	}
	return v.CodecName
}

func (v *VideoStream) GetCodecLongName() string {
	if v == nil {
		return ""
	}
	return v.CodecLongName
}

func (v *VideoStream) GetCodecTagString() *string {
	if v == nil {
		return nil
	}
	return v.CodecTagString
}

func (v *VideoStream) GetCodecTag() *string {
	if v == nil {
		return nil
	}
	return v.CodecTag
}

func (v *VideoStream) GetProfile() *string {
	if v == nil {
		return nil
	}
	return v.Profile
}

func (v *VideoStream) GetWidth() *int {
	if v == nil {
		return nil
	}
	return v.Width
}

func (v *VideoStream) GetHeight() *int {
	if v == nil {
		return nil
	}
	return v.Height
}

func (v *VideoStream) GetIsAvc() *bool {
	if v == nil {
		return nil
	}
	return v.IsAvc
}

func (v *VideoStream) GetID() *string {
	if v == nil {
		return nil
	}
	return v.ID
}

func (v *VideoStream) GetExtraProperties() map[string]interface{} {
	return v.extraProperties
}

func (v *VideoStream) UnmarshalJSON(data []byte) error {
	type unmarshaler VideoStream
	var value unmarshaler
	if err := json.Unmarshal(data, &value); err != nil {
		return err
	}
	*v = VideoStream(value)

	extraProperties, err := core.ExtractExtraProperties(data, *v)
	if err != nil {
		return err
	}
	v.extraProperties = extraProperties

	v._rawJSON = json.RawMessage(data)
	return nil
}

func (v *VideoStream) String() string {
	if len(v._rawJSON) > 0 {
		if value, err := core.StringifyJSON(v._rawJSON); err == nil {
			return value
		}
	}
	if value, err := core.StringifyJSON(v); err == nil {
		return value
	}
	return fmt.Sprintf("%#v", v)
}
