// This file was auto-generated by Fern from our API Definition.

package api

import (
	json "encoding/json"
	fmt "fmt"
	core "sdk/core"
)

type BodyCreateCustomVoiceCreateCustomVoicePost struct {
	RunID       *int    `json:"-" url:"run_id,omitempty"`
	VoiceName   string  `json:"voice_name" url:"-"`
	Gender      Gender  `json:"gender" url:"-"`
	Description *string `json:"description,omitempty" url:"-"`
	// By setting true, you consent to making this voice available for other users in the marketplace.
	PublishVoiceToMarketPlace *bool `json:"publish_voice_to_market_place,omitempty" url:"-"`
	Age                       *int  `json:"age,omitempty" url:"-"`
	// Language of the voice
	Language *Languages `json:"language,omitempty" url:"-"`
	// Enables advanced audio processing to enhance the clarity and quality of the cloned voice output. When set to `true`, additional processing is applied to improve the overall sound experience.
	EnhanceAudio *bool `json:"enhance_audio,omitempty" url:"-"`
}

type ListVoicesListVoicesGetRequest struct {
	RunID *int `json:"-" url:"run_id,omitempty"`
}

type CreateCustomVoiceOut struct {
	VoiceID int `json:"voice_id" url:"voice_id"`

	extraProperties map[string]interface{}
	_rawJSON        json.RawMessage
}

func (c *CreateCustomVoiceOut) GetVoiceID() int {
	if c == nil {
		return 0
	}
	return c.VoiceID
}

func (c *CreateCustomVoiceOut) GetExtraProperties() map[string]interface{} {
	return c.extraProperties
}

func (c *CreateCustomVoiceOut) UnmarshalJSON(data []byte) error {
	type unmarshaler CreateCustomVoiceOut
	var value unmarshaler
	if err := json.Unmarshal(data, &value); err != nil {
		return err
	}
	*c = CreateCustomVoiceOut(value)

	extraProperties, err := core.ExtractExtraProperties(data, *c)
	if err != nil {
		return err
	}
	c.extraProperties = extraProperties

	c._rawJSON = json.RawMessage(data)
	return nil
}

func (c *CreateCustomVoiceOut) String() string {
	if len(c._rawJSON) > 0 {
		if value, err := core.StringifyJSON(c._rawJSON); err == nil {
			return value
		}
	}
	if value, err := core.StringifyJSON(c); err == nil {
		return value
	}
	return fmt.Sprintf("%#v", c)
}

type Voice struct {
	ID          int        `json:"id" url:"id"`
	VoiceName   string     `json:"voice_name" url:"voice_name"`
	Gender      *int       `json:"gender,omitempty" url:"gender,omitempty"`
	Age         *int       `json:"age,omitempty" url:"age,omitempty"`
	Language    *Languages `json:"language,omitempty" url:"language,omitempty"`
	Transcript  *string    `json:"transcript,omitempty" url:"transcript,omitempty"`
	Description *string    `json:"description,omitempty" url:"description,omitempty"`
	IsPublished *bool      `json:"is_published,omitempty" url:"is_published,omitempty"`
	SignedURL   *string    `json:"signed_url,omitempty" url:"signed_url,omitempty"`

	extraProperties map[string]interface{}
	_rawJSON        json.RawMessage
}

func (v *Voice) GetID() int {
	if v == nil {
		return 0
	}
	return v.ID
}

func (v *Voice) GetVoiceName() string {
	if v == nil {
		return ""
	}
	return v.VoiceName
}

func (v *Voice) GetGender() *int {
	if v == nil {
		return nil
	}
	return v.Gender
}

func (v *Voice) GetAge() *int {
	if v == nil {
		return nil
	}
	return v.Age
}

func (v *Voice) GetLanguage() *Languages {
	if v == nil {
		return nil
	}
	return v.Language
}

func (v *Voice) GetTranscript() *string {
	if v == nil {
		return nil
	}
	return v.Transcript
}

func (v *Voice) GetDescription() *string {
	if v == nil {
		return nil
	}
	return v.Description
}

func (v *Voice) GetIsPublished() *bool {
	if v == nil {
		return nil
	}
	return v.IsPublished
}

func (v *Voice) GetSignedURL() *string {
	if v == nil {
		return nil
	}
	return v.SignedURL
}

func (v *Voice) GetExtraProperties() map[string]interface{} {
	return v.extraProperties
}

func (v *Voice) UnmarshalJSON(data []byte) error {
	type unmarshaler Voice
	var value unmarshaler
	if err := json.Unmarshal(data, &value); err != nil {
		return err
	}
	*v = Voice(value)

	extraProperties, err := core.ExtractExtraProperties(data, *v)
	if err != nil {
		return err
	}
	v.extraProperties = extraProperties

	v._rawJSON = json.RawMessage(data)
	return nil
}

func (v *Voice) String() string {
	if len(v._rawJSON) > 0 {
		if value, err := core.StringifyJSON(v._rawJSON); err == nil {
			return value
		}
	}
	if value, err := core.StringifyJSON(v); err == nil {
		return value
	}
	return fmt.Sprintf("%#v", v)
}

type ListVoicesListVoicesGetResponseItem struct {
	StringUnknownMap map[string]interface{}
	Voice            *Voice

	typ string
}

func NewListVoicesListVoicesGetResponseItemFromStringUnknownMap(value map[string]interface{}) *ListVoicesListVoicesGetResponseItem {
	return &ListVoicesListVoicesGetResponseItem{typ: "StringUnknownMap", StringUnknownMap: value}
}

func NewListVoicesListVoicesGetResponseItemFromVoice(value *Voice) *ListVoicesListVoicesGetResponseItem {
	return &ListVoicesListVoicesGetResponseItem{typ: "Voice", Voice: value}
}

func (l *ListVoicesListVoicesGetResponseItem) GetStringUnknownMap() map[string]interface{} {
	if l == nil {
		return nil
	}
	return l.StringUnknownMap
}

func (l *ListVoicesListVoicesGetResponseItem) GetVoice() *Voice {
	if l == nil {
		return nil
	}
	return l.Voice
}

func (l *ListVoicesListVoicesGetResponseItem) UnmarshalJSON(data []byte) error {
	var valueStringUnknownMap map[string]interface{}
	if err := json.Unmarshal(data, &valueStringUnknownMap); err == nil {
		l.typ = "StringUnknownMap"
		l.StringUnknownMap = valueStringUnknownMap
		return nil
	}
	valueVoice := new(Voice)
	if err := json.Unmarshal(data, &valueVoice); err == nil {
		l.typ = "Voice"
		l.Voice = valueVoice
		return nil
	}
	return fmt.Errorf("%s cannot be deserialized as a %T", data, l)
}

func (l ListVoicesListVoicesGetResponseItem) MarshalJSON() ([]byte, error) {
	if l.typ == "StringUnknownMap" || l.StringUnknownMap != nil {
		return json.Marshal(l.StringUnknownMap)
	}
	if l.typ == "Voice" || l.Voice != nil {
		return json.Marshal(l.Voice)
	}
	return nil, fmt.Errorf("type %T does not include a non-empty union type", l)
}

type ListVoicesListVoicesGetResponseItemVisitor interface {
	VisitStringUnknownMap(map[string]interface{}) error
	VisitVoice(*Voice) error
}

func (l *ListVoicesListVoicesGetResponseItem) Accept(visitor ListVoicesListVoicesGetResponseItemVisitor) error {
	if l.typ == "StringUnknownMap" || l.StringUnknownMap != nil {
		return visitor.VisitStringUnknownMap(l.StringUnknownMap)
	}
	if l.typ == "Voice" || l.Voice != nil {
		return visitor.VisitVoice(l.Voice)
	}
	return fmt.Errorf("type %T does not include a non-empty union type", l)
}
